/*
 * Copyright 2006-2026 Daniel Yuan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.elite.ir;

import elite.lang.Symbol;
import org.elite.eval.ELEngine;
import org.elite.eval.ELUtils;
import org.elite.eval.EvaluationContext;
import org.elite.eval.EvaluationException;
import org.elite.eval.ExternalImports;
import org.elite.eval.Frame;
import org.elite.eval.Runtime;
import org.elite.eval.StackTrace;
import org.elite.eval.StandaloneVariableMapper;
import org.elite.eval.TypeCoercion;
import org.elite.eval.UserException;
import org.elite.parser.ELNode;
import org.elite.resources.Resources;
import org.elite.util.DynamicClassLoader;
import org.elite.util.asm.AnnotationAssembly;
import org.elite.util.asm.AsmType;
import org.elite.util.asm.ClassAssembly;
import org.elite.util.asm.MethodAssembly;
import org.objectweb.asm.Label;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Handle;
import org.objectweb.asm.Type;
import javax.el.ELContext;
import javax.el.VariableMapper;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.lang.invoke.CallSite;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Stream;

import static org.elite.eval.ELUtils.*;
import static org.elite.ir.Opcode.*;
import static org.elite.resources.Resources.*;
import static org.objectweb.asm.Opcodes.ACC_ABSTRACT;
import static org.objectweb.asm.Opcodes.ACC_FINAL;
import static org.objectweb.asm.Opcodes.ACC_PRIVATE;
import static org.objectweb.asm.Opcodes.ACC_PROTECTED;
import static org.objectweb.asm.Opcodes.ACC_PUBLIC;
import static org.objectweb.asm.Opcodes.ACC_STATIC;
import static org.objectweb.asm.Opcodes.ACC_SUPER;
import static org.objectweb.asm.Opcodes.ACC_SYNTHETIC;
import static org.objectweb.asm.Opcodes.ACC_TRANSIENT;

public class BytecodeCompiler {

  private static final AtomicInteger CLASS_COUNTER = new AtomicInteger();

  private final String ProgramClassName;
  private final BytecodeConsumer consumer;

  private static final String CONSTANT_POOL_NAME = "$C";
  private final Map<Object, Integer> constantMap = new HashMap<>();

  private final Map<IRFunction, String> closureNames = new HashMap<>();
  private final Set<IRFunction> createdClosures = new HashSet<>();

  /**
   * JIT compile the {@code IRProgram} and load the generated bytecode via the
   * provided {@code loader}.
   */
  public static IRCompiledFunction compile(IRProgram program,
                                           DynamicClassLoader loader) {
    String name = "ELiteProgram$" + CLASS_COUNTER.incrementAndGet();
    var consumer = new JITBytecodeConsumer(loader);
    new BytecodeCompiler(name, consumer).compileProgram(program, null);
    return consumer.complete();
  }

  /**
   * Compile the {@code IRProgram} into bytecode. It's the responsibility of the
   * caller to provide a {@code BytecodeConsumer} to accept generated bytecode.
   *
   * <p>If an {@code ExternalImports} is provided, a main method is generated
   * to launch the program.
   */
  public static void compile(IRProgram program, String name,
                             BytecodeConsumer consumer,
                             ExternalImports imports) {
    new BytecodeCompiler(name, consumer).compileProgram(program, imports);
  }

  private BytecodeCompiler(String className, BytecodeConsumer consumer) {
    this.ProgramClassName = className;
    this.consumer = consumer;
  }

  private void compileProgram(IRProgram program, ExternalImports imports) {
    // Map functions to program class methods.
    int idx = 0;
    for (IRFunction f : program.functions()) {
      if (f == program.entry())
        f.internalName = "fn$main";
      else if (isJavaIdentifier(f.name()))
        f.internalName = "fn$" + f.name() + "$" + idx++;
      else
        f.internalName = "lambda$$" + idx++;
    }

    // Map elite class to Java class.
    for (IRClass c : program.classes()) {
      c.internalName = ProgramClassName + "$" + c.internalName;

      // Collect all class member functions.
      Map<IRFunction, ELNode.DEFINE> fmap = new HashMap<>();
      Stream.concat(Arrays.stream(c.node.cvars), Arrays.stream(c.node.ivars))
        .filter(var -> var.symbol.func != null)
        .forEach(var -> fmap.put(var.symbol.func, var));

      // If the function is a class member, must use the function name (may
      // mangle), otherwise, for named lambda, use "lambda$name$0" for internal
      // name, otherwise, just use "lambda$$0" for internal name.
      for (IRFunction f : c.functions()) {
        ELNode.DEFINE def = fmap.get(f);
        if (def != null)
          f.internalName = mangle(def.id);
        else if (isJavaIdentifier(f.name()))
          f.internalName = "lambda$" + f.name() + "$" + idx++;
        else
          f.internalName = "lambda$$" + idx++;
      }
    }

    // Create program class.
    ClassAssembly cc = new ClassAssembly(ACC_PUBLIC | ACC_FINAL | ACC_SUPER,
                                         ProgramClassName, Object.class, null);
    attachSource(cc, program.entry().debugInfo());

    // Default constructor.
    cc.newMethod(ACC_PRIVATE, "<init>", "()V", null)
      .THIS()
      .INVOKESPECIAL(Object.class, "<init>", Void.TYPE, NO_ARGS)
      .RETURN()
      .end();

    // Compile program functions. This includes program entry function.
    for (IRFunction f : program.functions()) {
      compileFunction(cc, f);
    }

    // Compile classes.
    for (IRClass clazz : program.classes()) {
      compileClass(clazz);
    }

    // Compile final persistent constant pool.
    compileConstantPool(cc);

    // Compile main method.
    if (imports != null)
      compileMain(cc, imports, program.entry().debugInfo());

    // Produce the final compiled program.
    consumer.acceptProgram(ProgramClassName, cc.end());
  }

  private static void attachSource(ClassAssembly cc, DebugInfo debug) {
    attachSource(cc, debug != null ? debug.file() : null);
  }

  private static void attachSource(ClassAssembly cc, String filename) {
    if (filename != null) {
      int sep = filename.lastIndexOf('/');
      if (sep != -1)
        filename = filename.substring(sep + 1);
      cc.getImpl().visitSource(filename, null);
    }
  }

  private void compileFunction(ClassAssembly cc, IRFunction f) {
    // The function method:
    // public static Object fn$func$0(
    //    EvaluationContext env, Object[] args)
    MethodAssembly mc = cc.newMethod(
      ACC_PUBLIC | ACC_STATIC | ACC_FINAL, f.internalName, Object.class,
      EvaluationContext.class, Object[].class);

    AnnotationAssembly ac = mc.ANNOTATION(MetaMethod.class, true);
    ac.FIELD("name", f.name())
      .FIELD("arity", f.paramCount())
      .FIELD("varargs", f.isVarArgs())
      .ARRAY("parameterNames", f.paramNames());
    emitDefaultValues(ac, f.defaultValues());
    ac.end();

    new FunctionCompiler(f, ProgramClassName, true, Object.class, mc).compile();
  }

  private void emitDefaultValues(AnnotationAssembly ac, Object[] defaultValues) {
    if (defaultValues == null)
      return;

    AnnotationAssembly dv = ac.ARRAY("defaultValues");
    for (Object value : defaultValues) {
      if (value == null) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "NULL")
          .end();
      } else if (value instanceof List<?> ls && ls.isEmpty()) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "NIL")
          .end();
      } else if (value instanceof Boolean) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "BOOL")
          .FIELD("boolValue", value)
          .end();
      } else if (value instanceof Character) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "CHAR")
          .FIELD("charValue", value)
          .end();
      } else if (value instanceof Integer || value instanceof Byte ||
                 value instanceof Short) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "INT")
          .FIELD("intValue", ((Number)value).intValue())
          .end();
      } else if (value instanceof Long) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "LONG")
          .FIELD("longValue", value)
          .end();
      } else if (value instanceof Float) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "FLOAT")
          .FIELD("floatValue", value)
          .end();
      } else if (value instanceof Double) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "DOUBLE")
          .FIELD("doubleValue", value)
          .end();
      } else if (value instanceof String) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "STRING")
          .FIELD("stringValue", value)
          .end();
      } else if (value instanceof Symbol symbol) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "SYMBOL")
          .FIELD("stringValue", symbol.getName())
          .end();
      } else if (value instanceof Class) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "CLASS")
          .FIELD("classValue", Type.getType((Class<?>)value))
          .end();
      } else if (value instanceof IRClass irc) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "CLASS")
          .FIELD("classValue", Type.getType(
            AsmType.toDescriptor(irc.internalName)))
          .end();
      } else if (value instanceof Field field) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "FIELD")
          .FIELD("classValue", Type.getType(field.getDeclaringClass()))
          .FIELD("stringValue", field.getName())
          .end();
      } else if (value instanceof Descriptors.Field field) {
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "FIELD")
          .FIELD("classValue", Type.getType(
            AsmType.toDescriptor(field.clazz().internalName)))
          .FIELD("stringValue", field.field())
          .end();
      } else {
        int index = putConstant(value);
        dv.ANNOTATION(null, Value.class)
          .ENUM("kind", ValueKind.class, "CONST")
          .FIELD("classValue", Type.getType(
            AsmType.toDescriptor(ProgramClassName)))
          .FIELD("intValue", index)
          .end();
      }
    }
    dv.end();
  }

  private void compileClass(IRClass clazz) {
    new ClassCompiler(clazz).compile();
  }

  private void compileConstantPool(ClassAssembly cc) {
    if (constantMap.isEmpty())
      return;

    cc.addField(ACC_PUBLIC | ACC_STATIC | ACC_FINAL, CONSTANT_POOL_NAME,
                Object[].class);

    MethodAssembly mc = cc.newMethod(ACC_STATIC, "<clinit>", "()V", null);

    mc.PUSH(constantMap.size())
      .ANEWARRAY(Object.class)
      .PUTSTATIC(ProgramClassName, CONSTANT_POOL_NAME, Object[].class);

    for (var e : constantMap.entrySet()) {
      try {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        ObjectOutputStream oout = new ObjectOutputStream(out);
        oout.writeObject(e.getKey());
        oout.close();
        String encoded = Base64.getEncoder().encodeToString(out.toByteArray());

        mc.GETSTATIC(ProgramClassName, CONSTANT_POOL_NAME, Object[].class)
          .PUSH(e.getValue())
          .LDC(encoded)
          .INVOKESTATIC(Runtime.class, "decodeObject", Object.class,
                        String.class)
          .AASTORE();
      } catch (IOException ex) {
        throw new RuntimeException(ex);
      }
    }

    mc.RETURN()
      .end();
  }

  private int putConstant(Object value) {
    return constantMap.computeIfAbsent(value, k -> constantMap.size());
  }

  private void loadConstant(MethodAssembly mc, Object value) {
    int index = putConstant(value);
    mc.GETSTATIC(ProgramClassName, CONSTANT_POOL_NAME, Object[].class)
      .PUSH(index)
      .AALOAD();
  }

  private void compileMain(ClassAssembly cc, ExternalImports imports,
                           DebugInfo debug) {
    // public static void main(String[] args) {
    //     VariableMapper vm = new StandaloneVariableMapper(args);
    //     ELContext elctx = ELEngine.createELContxt(vm);
    //     elctx = new ExternalImports()
    //         .addModules()
    //         .addFunctions()
    //         .addPackages()
    //         .importExternal(elctx)
    //     ELEngine.setCurrentELContext(elctx);
    //     EvaluationContext env = new EvaluationContext(elctx);
    //     fn$main(env, new Object[0]);
    // }

    MethodAssembly mc = cc.newMethod(ACC_PUBLIC | ACC_STATIC, "main",
                                     "([Ljava/lang/String;)V", null);

    if (debug != null) {
      int line = debug.lineForPC(0);
      if (line != 0)
        mc.getImpl().visitLineNumber(line, mc.label());
    }

    // Placeholder for final EvaluationContext.
    mc.NEW(EvaluationContext.class)
      .DUP();

    // Import externals.
    mc.NEW_INSTANCE(ExternalImports.class);
    for (ExternalImports.Module mod : imports.getModules()) {
      mc.LDC(mod.getName());
      if (mod.getPrefix() != null)
        mc.LDC(mod.getPrefix());
      else
        mc.ACONST_NULL();
      mc.INVOKEVIRTUAL(ExternalImports.class, "addModule",
                       ExternalImports.class, String.class, String.class);
    }
    for (String lib : imports.getLibraries()) {
      mc.LDC(lib)
        .INVOKEVIRTUAL(ExternalImports.class, "addLibrary",
                       ExternalImports.class, String.class);
    }
    for (String imp : imports.getImports()) {
      mc.LDC(imp)
        .INVOKEVIRTUAL(ExternalImports.class, "addImport",
                       ExternalImports.class, String.class);
    }

    // Create ELContext using StandaloneVariableMapper.
    mc.NEW(StandaloneVariableMapper.class)
      .DUP()
      .ALOAD(0)
      .INVOKESPECIAL(StandaloneVariableMapper.class, "<init>", Void.TYPE,
                     String[].class)
      .INVOKESTATIC(ELEngine.class, "createELContext", ELContext.class,
                    VariableMapper.class)

      // Import externals into newly created ELContext.
      .INVOKEVIRTUAL(ExternalImports.class, "importExternals",
                     ELContext.class, ELContext.class)
      .DUP()
      .INVOKESTATIC(ELEngine.class, "setCurrentELContext", ELContext.class,
                    ELContext.class)
      .POP()

      // Create a pseudo frame to avoid NPE.
      .DUP()
      .LDC("")
      .ACONST_NULL()
      .ICONST_0()
      .INVOKESTATIC(StackTrace.class, "addFrame", Frame.class,
                    ELContext.class, String.class, String.class, int.class)
      .POP()

      // Create EvaluationContext using newly created ELContext.
      .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                     ELContext.class)

      // Invoke the main entry using newly crated EvaluationContext and an empty
      // argument list.
      .ICONST_0()
      .ANEWARRAY(Object.class)
      .INVOKESTATIC(ProgramClassName, "fn$main", Object.class,
                    EvaluationContext.class, Object[].class)
      .POP()
      .RETURN()
      .end();
  }

  private String getClosureName(IRFunction closure) {
    return closureNames.computeIfAbsent(closure, k -> {
      String ownerName = closure.owner() != null ? closure.owner().internalName
                                                 : ProgramClassName;
      return ownerName + "$Closure$" +
             (isJavaIdentifier(closure.name()) ? closure.name() : "") +
             "$" + CLASS_COUNTER.getAndIncrement();
    });
  }

  /*--------------------------------------------------------------------------*/

  /**
   * Inner class for class compilation.
   */
  private class ClassCompiler {
    private final IRClass clazz;
    private final String className;
    private final String rootBaseClass;
    private final Map<String, IRFunction> vmap = new HashMap<>();

    ClassCompiler(IRClass clazz) {
      this.clazz = clazz;
      this.className = clazz.internalName;

      // Find the root base class. We will put some shared fields in this root
      // base class.
      if (clazz.base instanceof IRClass) {
        for (IRClass c = clazz; ; ) {
          if (c.base instanceof IRClass) {
            c = (IRClass)c.base;
          } else {
            rootBaseClass = c.internalName;
            break;
          }
        }
      } else {
        rootBaseClass = className;
      }
    }

    void compile() {
      Map<IRFunction, ELNode.DEFINE> fmap = new HashMap<>();
      for (ELNode.DEFINE var : clazz.node.cvars) {
        if (var.expr instanceof ELNode.LAMBDA fn) {
          fmap.put(fn.symbol.func, var);
        }
      }
      for (ELNode.DEFINE var : clazz.node.ivars) {
        if (var.expr instanceof ELNode.LAMBDA fn) {
          fmap.put(fn.symbol.func, var);
          vmap.put(var.id, fn.symbol.func);
        }
      }

      String baseName = clazz.base instanceof IRClass
                        ? ((IRClass)clazz.base).internalName
                        : ((Class<?>)clazz.base).getName();

      Set<String> interfaces = new LinkedHashSet<>();
      if (clazz.interfaces != null) {
        for (Class<?> i : clazz.interfaces)
          interfaces.add(i.getName());
      }

      if (isDataClass(clazz))
        interfaces.add("java.io.Serializable");

      boolean isComparable = false;
      if (!interfaces.contains("java.lang.Comparable") &&
          vmap.containsKey("<=>") ||
          ((vmap.containsKey("equals") || vmap.containsKey("==")) &&
           vmap.containsKey("<"))) {
        // If a class defines <=> procedure then this class is a Comparable
        // object. The compareTo method of Comparable interface forwards to the
        // <=> procedure.
        //
        // If a class defines equals and < procedure then this class is a
        // Comparable object. The compareTo method of Comparable interface is
        // implemented using equals and < procedure.
        isComparable = true;
        interfaces.add("java.lang.Comparable");
      }

      ELNode.METASET meta = clazz.node.symbol.def.meta;
      int access = meta == null ? 0 : meta.modifiers;
      if ((access & ACC_PRIVATE) == 0)
        access |= ACC_PUBLIC;
      ClassAssembly cc = new ClassAssembly(access | ACC_SUPER, className,
                                           baseName,
                                           interfaces.toArray(new String[0]));
      attachSource(cc, clazz.node.file);

      if (clazz.host != null)
        cc.getImpl().visitNestHost(AsmType.toInternalName(clazz.host.internalName));
      for (IRClass inner : clazz.inners)
        cc.getImpl().visitNestMember(AsmType.toInternalName(inner.internalName));

      // Add annotation for ELite class.
      cc.ANNOTATION(MetaClass.class, true)
        .FIELD("name", clazz.name)
        .end();

      // Add static and instance fields.
      for (ELNode.DEFINE var : clazz.node.cvars) {
        if (!(var.expr instanceof ELNode.LAMBDA) &&
            !(var.expr instanceof ELNode.CLASSDEF)) {
          access = var.meta == null ? ACC_PUBLIC : var.meta.modifiers;
          if ((access & (ACC_PRIVATE|ACC_PROTECTED)) == 0)
            access |= ACC_PUBLIC;
          cc.addField(access | ACC_STATIC, var.id, Object.class);
        }
      }
      if (clazz.node.vars != null) {
        for (ELNode.DEFINE var : clazz.node.vars) {
          access = var.meta == null ? ACC_PUBLIC : var.meta.modifiers;
          if ((access & (ACC_PRIVATE|ACC_PROTECTED)) == 0)
            access |= ACC_PUBLIC;
          cc.addField(access, var.id, Object.class);
        }
      }
      for (ELNode.DEFINE var : clazz.node.ivars) {
        if (!(var.expr instanceof ELNode.LAMBDA) &&
            !(var.expr instanceof ELNode.CLASSDEF)) {
          access = var.meta == null ? 0 : var.meta.modifiers;
          if ((access & (ACC_PRIVATE|ACC_PROTECTED)) == 0)
            access |= ACC_PUBLIC;
          cc.addField(access, var.id, Object.class);
        }
      }

      // Constructor.
      IRFunction initFunc = clazz.init_proc.symbol.func;
      access = clazz.isSingleton() ? ACC_PRIVATE : ACC_PUBLIC;
      MethodAssembly mc;

      if (clazz.outer != null) {
        String outerDescriptor = AsmType.toDescriptor(clazz.outer.internalName);
        cc.addField(ACC_FINAL | ACC_SYNTHETIC, "$outer", outerDescriptor);
        mc = cc.newMethod(access, "<init>",
          "(" + AsmType.getDescriptor(EvaluationContext.class) +
          AsmType.getDescriptor(Object[].class) +
          outerDescriptor + ")V", null);
        mc.THIS()
          .ALOAD(3)
          .PUTFIELD(className, "$outer", outerDescriptor);
      } else {
        mc = cc.newMethod(access, "<init>", Void.TYPE, EvaluationContext.class,
                          Object[].class);
      }

      AnnotationAssembly ac = mc.ANNOTATION(MetaMethod.class, true);
      ac.FIELD("name", clazz.name)
        .FIELD("arity", initFunc.paramCount())
        .FIELD("varargs", initFunc.isVarArgs())
        .ARRAY("parameterNames", initFunc.paramNames());
      emitDefaultValues(ac, initFunc.defaultValues());
      ac.end();

      if (className.equals(rootBaseClass)) {
        // Add $context field to save the ELContext for methods invoked without
        // an evaluation context, such as interface methods or Object methods.
        cc.addField(ACC_PROTECTED | ACC_FINAL | ACC_TRANSIENT, "$context",
                    ELContext.class);
        mc.THIS()
          .ALOAD(1)
          .INVOKEVIRTUAL(EvaluationContext.class, "getELContext",
                         ELContext.class)
          .PUTFIELD(className, "$context", ELContext.class);
      }

      new FunctionCompiler(initFunc, className, false, Void.TYPE, mc).compile();

      // Class initializer.
      if (clazz.clinit_proc != null || clazz.isSingleton()) {
        mc = cc.newMethod(ACC_PUBLIC | ACC_STATIC, "<clinit>", Void.TYPE);
        mc.NEW(EvaluationContext.class)
          .DUP()
          .INVOKESTATIC(ELEngine.class, "getCurrentELContext", ELContext.class)
          .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                         ELContext.class)
          .ASTORE(0);

        if (clazz.isSingleton()) {
          cc.addField(ACC_PUBLIC | ACC_STATIC | ACC_FINAL, "$singleton",
                      Object.class);
          mc.NEW(className)
            .DUP()
            .ALOAD(0)
            .ACONST_NULL()
            .INVOKESPECIAL(className, "<init>", Void.TYPE,
                           EvaluationContext.class, Object[].class)
            .PUTSTATIC(className, "$singleton", Object.class);
        }

        if (clazz.clinit_proc != null) {
          IRFunction clinitFunc = clazz.clinit_proc.symbol.func;
          mc.ICONST_0()
            .ANEWARRAY(Object.class)
            .ASTORE(1);
          new FunctionCompiler(clinitFunc, className, true, Void.TYPE, mc)
            .compile();
        } else {
          mc.RETURN();
          mc.end();
        }
      }

      // Generate member functions.
      for (IRFunction fn : clazz.functions()) {
        ELNode.DEFINE def = fmap.get(fn);
        if (def != null && (def.id.equals("toString") ||
                            def.id.equals("equals") ||
                            def.id.equals("hashCode")))
          continue; // generated differently

        access = def != null && def.meta != null ? def.meta.modifiers : 0;
        if ((access & (ACC_PRIVATE | ACC_PROTECTED)) == 0)
          access |= ACC_PUBLIC;
        if (def == null && fn.isStatic())
          access |= ACC_STATIC;
        mc = cc.newMethod(access, fn.internalName, Object.class,
                          EvaluationContext.class, Object[].class);

        // Add annotation for member attributes.
        ac = mc.ANNOTATION(MetaMethod.class, true);
        ac.FIELD("name", fn.name())
          .FIELD("arity", fn.paramCount())
          .FIELD("varargs", fn.isVarArgs())
          .ARRAY("parameterNames", fn.paramNames());
        emitDefaultValues(ac, fn.defaultValues());
        ac.end();

        if ((access & ACC_ABSTRACT) == 0) {
          new FunctionCompiler(fn, className, (access & ACC_STATIC) != 0,
                               Object.class, mc).compile();
        }
      }

      // Compile override methods derived from base class and interfaces.
      compileOverrideMethods(cc);

      // Generate toString method.
      if (vmap.containsKey("toString") || clazz.node.vars != null) {
        compileToStringMethod(cc);
      }

      // Generate equals method.
      if (vmap.containsKey("equals") || vmap.containsKey("==") ||
          clazz.node.vars != null) {
        compileEqualsMethod(cc);
      }

      // Generate hashCode method.
      if (vmap.containsKey("hashCode") || clazz.node.vars != null) {
        compileHashCodeMethod(cc);
      }

      // Generate compareTo method.
      if (isComparable) {
        compileCompareToMethod(cc);
      }

      consumer.acceptClass(className, cc.end());
    }

    private static boolean isDataClass(IRClass clazz) {
      ELNode.METASET meta = clazz.node.symbol.def.meta;
      return meta != null &&
        Arrays.stream(meta.metadata).anyMatch(md -> md.type.equals("data"));
    }

    private record MethodRecord(String name, List<Class<?>> paramTypes) {
      MethodRecord(Method m) {
        this(m.getName(), Arrays.asList(m.getParameterTypes()));
      }
    }

    private void compileOverrideMethods(ClassAssembly cc) {
      Map<MethodRecord, Method> methods = new HashMap<>();
      collectOverrideMethods(methods);
      if (methods.isEmpty())
        return;

      for (Method m : methods.values()) {
        IRFunction fn = vmap.get(m.getName());
        if (fn != null && fn.paramCount() == m.getParameterCount()) {
          MethodAssembly mc = cc.newMethod(ACC_PUBLIC, m);
          Class<?>[] paramTypes = m.getParameterTypes();
          Class<?> returnType = m.getReturnType();
          int ctxSlot = paramTypes.length + 1; // this, params..., ctx

          mc.THIS()
            .GETFIELD(rootBaseClass, "$context", ELContext.class);
          if (returnType != Void.TYPE && returnType != Object.class)
            mc.DUP(); // for coerce
          mc.ASTORE(ctxSlot);

          mc.THIS()
            .NEW(EvaluationContext.class)
            .DUP()
            .ALOAD(ctxSlot)
            .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                           ELContext.class)

            .PUSH(paramTypes.length)
            .ANEWARRAY(Object.class);
          for (int i = 0; i < paramTypes.length; i++) {
            mc.DUP()
              .PUSH(i)
              .XLOAD(i + 1, paramTypes[i])
              .BOX(paramTypes[i])
              .AASTORE();
          }

          mc.INVOKEVIRTUAL(className, m.getName(), Object.class,
                           EvaluationContext.class, Object[].class);
          if (returnType == Void.TYPE) {
            mc.POP().RETURN();
          } else if (returnType == Object.class) {
            mc.ARETURN();
          } else {
            mc.INVOKEDYNAMIC(FunctionCompiler.COERCE_BOOTSTRAP, "coerce",
                             AsmType.getMethodDescriptor(
                               returnType, ELContext.class, Object.class));
            mc.XRETURN(returnType);
          }
          mc.end();
        }
      }
    }

    private void collectOverrideMethods(Map<MethodRecord, Method> methods) {
      if (clazz.base instanceof Class<?> c && c != Object.class) {
        for (; c != Object.class; c = c.getSuperclass()) {
          for (Method m : c.getDeclaredMethods()) {
            int modifiers = m.getModifiers();
            if ((Modifier.isPublic(modifiers) ||
                 Modifier.isProtected(modifiers)) &&
                !Modifier.isStatic(modifiers) &&
                !Modifier.isFinal(modifiers)) {
              methods.putIfAbsent(new MethodRecord(m), m);
            }
          }
        }
      }

      if (clazz.interfaces != null) {
        for (Class<?> iface : clazz.interfaces) {
          for (Method m : iface.getMethods()) {
            int modifiers = m.getModifiers();
            if ((Modifier.isPublic(modifiers) ||
                 Modifier.isProtected(modifiers)) &&
                !Modifier.isStatic(modifiers))
              methods.putIfAbsent(new MethodRecord(m), m);
          }
        }
      }
    }

    private void compileToStringMethod(ClassAssembly cc) {
      MethodAssembly mc = cc.newMethod(ACC_PUBLIC, "toString", String.class);

      IRFunction fn = vmap.get("toString");
      if (fn != null) {
        mc.NEW(EvaluationContext.class)
          .DUP()
          .THIS()
          .GETFIELD(rootBaseClass, "$context", ELContext.class)
          .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                         ELContext.class)
          .ASTORE(1)
          .ICONST_0()
          .ANEWARRAY(Object.class)
          .ASTORE(2);
        new FunctionCompiler(fn, className, false, String.class, mc).compile();
      } else {
        mc.THIS()
          .GETFIELD(rootBaseClass, "$context", ELContext.class)
          .ASTORE(1);

        mc.NEW_INSTANCE(StringBuilder.class)
          .LDC(clazz.name + "(")
          .INVOKEVIRTUAL(StringBuilder.class, "append", StringBuilder.class,
                         String.class);

        assert clazz.node.vars != null;
        for (int i = 0; i < clazz.node.vars.length; i++) {
          Label b1 = new Label(), b2 = new Label();
          if (i > 0) {
            mc.LDC(", ")
              .INVOKEVIRTUAL(StringBuilder.class, "append", StringBuilder.class,
                             String.class);
          }
          mc.THIS()
            .GETFIELD(className, clazz.node.vars[i].id, Object.class)
            .DUP()
            .INSTANCEOF(String.class)
            .IFEQ(b1)
            .CHECKCAST(String.class)
            .INVOKESTATIC(ELUtils.class, "escape", StringBuilder.class,
                          StringBuilder.class, String.class)
            .GOTO(b2)
          .label(b1)
            .ALOAD(1)
            .SWAP()
            .INVOKEDYNAMIC(FunctionCompiler.COERCE_BOOTSTRAP, "coerce",
                           AsmType.getMethodDescriptor(
                             String.class, ELContext.class, Object.class))
            .INVOKEVIRTUAL(StringBuilder.class, "append", StringBuilder.class,
                           String.class)
          .label(b2);
        }

        mc.LDC(")")
          .INVOKEVIRTUAL(StringBuilder.class, "append", StringBuilder.class,
                         String.class)
          .INVOKEVIRTUAL(StringBuilder.class, "toString", String.class)
          .ARETURN()
          .end();
      }
    }

    private void compileEqualsMethod(ClassAssembly cc) {
      MethodAssembly mc = cc.newMethod(ACC_PUBLIC, "equals", Boolean.TYPE,
                                       Object.class);

      if (vmap.containsKey("equals") && !vmap.containsKey("==")) {
        mc.NEW(EvaluationContext.class)
          .DUP()
          .THIS()
          .GETFIELD(rootBaseClass, "$context", ELContext.class)
          .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                         ELContext.class)
          .ASTORE(1)
          .ICONST_1()
          .ANEWARRAY(Object.class)
          .DUP()
          .ICONST_0()
          .ALOAD(1)
          .AASTORE()
          .ASTORE(2);

        IRFunction fn = vmap.getOrDefault("equals", vmap.get("=="));
        new FunctionCompiler(fn, className, false, Boolean.TYPE, mc).compile();
      } else {
        Label exit = new Label();
        mc.ALOAD(1)
          .INSTANCEOF(className)
          .IFEQ(exit)
          .ALOAD(1)
          .CHECKCAST(className)
          .ASTORE(2);

        assert clazz.node.vars != null;
        for (ELNode.DEFINE var : clazz.node.vars) {
          mc.THIS()
            .GETFIELD(className, var.id, Object.class)
            .ALOAD(2)
            .GETFIELD(className, var.id, Object.class)
            .INVOKESTATIC(Objects.class, "equals", Boolean.TYPE, Object.class,
                          Object.class)
            .IFEQ(exit);
        }

        mc.TRUE()
          .IRETURN();

        mc.label(exit)
          .FALSE()
          .IRETURN()
          .end();
      }
    }

    private void compileHashCodeMethod(ClassAssembly cc) {
      MethodAssembly mc = cc.newMethod(ACC_PUBLIC, "hashCode", Integer.TYPE);

      IRFunction fn = vmap.get("hashCode");
      if (fn != null) {
        mc.NEW(EvaluationContext.class)
          .DUP()
          .THIS()
          .GETFIELD(rootBaseClass, "$context", ELContext.class)
          .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                         ELContext.class)
          .ASTORE(1)
          .ICONST_0()
          .ANEWARRAY(Object.class)
          .ASTORE(2);
        new FunctionCompiler(fn, className, false, Integer.TYPE, mc).compile();
      } else {
        assert clazz.node.vars != null;
        mc.ICONST_1();
        for (ELNode.DEFINE var : clazz.node.vars) {
          Label b1 = new Label(), b2 = new Label();
          mc.PUSH(31)
            .IMUL()
            .THIS()
            .GETFIELD(className, var.id, Object.class)
            .DUP()
            .IFNONNULL(b1)
            .POP()
            .ICONST_0()
            .GOTO(b2)
            .label(b1)
            .INVOKEVIRTUAL(Object.class, "hashCode", Integer.TYPE)
            .label(b2)
            .IADD();
        }
        mc.IRETURN().end();
      }
    }

    private void compileCompareToMethod(ClassAssembly cc) {
      if (vmap.containsKey("<=>")) {
        // Delegate compareTo to the <=> procedure.
        IRFunction threeWay = vmap.get("<=>");
        cc.newMethod(ACC_PUBLIC, "compareTo", Integer.TYPE, Object.class)
          .THIS()
          .NEW(EvaluationContext.class)
          .DUP()
          .THIS()
          .GETFIELD(rootBaseClass, "$context", ELContext.class)
          .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                         ELContext.class)
          .ICONST_1()
          .ANEWARRAY(Object.class)
          .DUP()
          .ICONST_0()
          .ALOAD(1)
          .CHECKCAST(className)
          .AASTORE()
          .INVOKEVIRTUAL(className, threeWay.internalName, Object.class,
                         EvaluationContext.class, Object[].class)
          .UNBOX(Integer.TYPE)
          .IRETURN()
          .end();
      } else {
        IRFunction less = vmap.get("<");
        assert less != null;
        Label b1 = new Label(), b2 = new Label(), exit = new Label();

        cc.newMethod(ACC_PUBLIC, "compareTo", Integer.TYPE, Object.class)
          .THIS()
          .ALOAD(1)
          .INVOKEVIRTUAL(Object.class, "equals", Boolean.TYPE, Object.class)
          .IFEQ(b1)
          .ICONST_0()
          .GOTO(exit)
          .label(b1)
          .THIS()
          .NEW(EvaluationContext.class)
          .DUP()
          .THIS()
          .GETFIELD(rootBaseClass, "$context", ELContext.class)
          .INVOKESPECIAL(EvaluationContext.class, "<init>", Void.TYPE,
                         ELContext.class)
          .ICONST_1()
          .ANEWARRAY(Object.class)
          .DUP()
          .ICONST_0()
          .ALOAD(1)
          .CHECKCAST(className)
          .AASTORE()
          .INVOKEVIRTUAL(className, less.internalName, Object.class,
                         EvaluationContext.class, Object[].class)
          .UNBOX(Boolean.TYPE)
          .IFEQ(b2)
          .ICONST_M1()
          .GOTO(exit)
          .label(b2)
          .ICONST_1()
          .label(exit)
          .IRETURN()
          .end();
      }
    }
  }

  /*--------------------------------------------------------------------------*/

  /**
   * Inner class for function compilation.
   */
  private class FunctionCompiler {
    private final IRFunction     fn;
    private final String         currentClassName;
    private final boolean        isStatic;
    private final Class<?>       returnType;
    private final MethodAssembly mc;
    private final Label[]        blockLabels;

    FunctionCompiler(IRFunction fn, String className, boolean isStatic,
                     Class<?> returnType, MethodAssembly mc) {
      this.fn = fn;
      this.currentClassName = className;
      this.isStatic = isStatic;
      this.returnType = returnType;
      this.mc = mc;
      
      this.blockLabels = new Label[fn.blockCount()];
      for (int i = 0; i < fn.blockCount(); i++)
        blockLabels[i] = new Label();
    }
    
    private int S_ENV() {
      return isStatic ? 0 : 1;
    }
    
    private int S_ARGS() {
      return isStatic ? 1 : 2;
    }
    
    private int S_CTX() {
      return isStatic ? 2 : 3;
    }
    
    private int SLOT(int n) {
      return (isStatic ? 3 : 4) + n;
    }
    
    private int TMP_SLOT() {
      return SLOT(0) + fn.maxLocals();
    }
  
    void compile() {
      // Store ELContext to local slot.
      mc.ALOAD(S_ENV())
        .INVOKEVIRTUAL(EvaluationContext.class, "getELContext", ELContext.class)
        .ASTORE(S_CTX());
  
      // Copy arguments to local slots.
      if (fn.paramCount() != 0) {
        mc.ALOAD(S_ARGS());
        for (int i = 0; i < fn.paramCount(); i++) {
          if (i != fn.paramCount() - 1)
            mc.DUP();
          mc.PUSH(i)
            .AALOAD()
            .ASTORE(SLOT(i));
        }
      }
  
      // Compile IR into Java bytecode.
      DebugInfo debug = fn.debugInfo();
      int currentLine = 0;
  
      InstructionView v = new InstructionView(fn.code(), 0);
      for (; v.inBounds(); v.advance()) {
        int blockId = fn.blockOfPc(v.offset());
        if (blockId != -1)
          mc.label(blockLabels[blockId]);
  
        // Emit line number if changed from previous instruction.
        if (debug != null) {
          int line = debug.lineForPC(v.offset());
          if (line != 0 && line != currentLine) {
            currentLine = line;
            mc.getImpl().visitLineNumber(line, mc.label());
          }
        }
  
        compileInstruction(v);
      }
  
      mc.end();
    }
  
    private void compileInstruction(InstructionView v) {
      switch (v.opcode()) {
      case NOP -> {}
      case DUP -> mc.DUP();
      case POP -> mc.POP();
  
      case PUSH_CONST -> {
        Object value = fn.getConstant(v.poolIndex());
        if (value instanceof Boolean || value instanceof Byte ||
            value instanceof Short   || value instanceof Character ||
            value instanceof Integer || value instanceof Long ||
            value instanceof Float   || value instanceof Double) {
          emitPushPrimitive(v, value);
        } else if (value instanceof String) {
          emitPushString(v, (String)value);
        } else if (value instanceof Class<?> c) {
          mc.LDC(Type.getType(c));
        } else if (value instanceof IRClass irc) {
          mc.LDC(Type.getType(AsmType.toDescriptor(irc.internalName)));
        } else if (value instanceof Symbol sym) {
          mc.LDC(sym.getName())
            .INVOKESTATIC(Symbol.class, "valueOf", Symbol.class, String.class);
        } else {
          // Load constant from constant pool.
          loadConstant(mc, value);
        }
      }
  
      case PUSH_TRUE ->
        mc.GETSTATIC(Boolean.class, "TRUE", Boolean.class);
      case PUSH_FALSE ->
        mc.GETSTATIC(Boolean.class, "FALSE", Boolean.class);
      case PUSH_NULL ->
        mc.ACONST_NULL();

      case PUSH_THIS ->
        mc.THIS();
      case PUSH_ENV ->
        mc.ALOAD(S_ENV());
      case PUSH_CTX ->
        mc.ALOAD(S_CTX());
  
      case PUSH_VAR ->
        mc.ALOAD(SLOT(v.varIndex()));
      case STORE_VAR ->
        mc.DUP().ASTORE(SLOT(v.varIndex()));
      case STORE_VAR_POP ->
        mc.ASTORE(SLOT(v.varIndex()));
  
      case DEFINE_GLOBAL ->
        mc.LDC(fn.getConstant(v.poolIndex()))
          .PUSH(v.payload())
          .ALOAD(S_ENV())
          .INVOKESTATIC(Runtime.class, "defineGlobal", void.class,
                        Object.class, String.class, Boolean.TYPE,
                        EvaluationContext.class);
      case PUSH_GLOBAL ->
        mc.LDC(fn.getConstant(v.poolIndex()))
          .ALOAD(S_ENV())
          .INVOKESTATIC(Runtime.class, "resolveGlobal", Object.class,
                        String.class, EvaluationContext.class);
      case STORE_GLOBAL ->
        mc.LDC(fn.getConstant(v.poolIndex()))
          .ALOAD(S_ENV())
          .INVOKESTATIC(Runtime.class, "storeGlobal", Object.class,
                        Object.class, String.class, EvaluationContext.class);
  
      case ADD    -> emitBinary(v, "+",         Object.class);
      case SUB    -> emitBinary(v, "-",         Object.class);
      case MUL    -> emitBinary(v, "*",         Object.class);
      case DIV    -> emitBinary(v, "/",         Object.class);
      case IDIV   -> emitBinary(v, "__div__",   Object.class);
      case REM    -> emitBinary(v, "%",         Object.class);
      case POW    -> emitBinary(v, "^",         Object.class);
      case EQ     -> emitBinary(v, "==",        Boolean.TYPE);
      case NE     -> emitBinary(v, "!=",        Boolean.TYPE);
      case LT     -> emitBinary(v, "<",         Boolean.TYPE);
      case LE     -> emitBinary(v, "<=",        Boolean.TYPE);
      case GT     -> emitBinary(v, ">",         Boolean.TYPE);
      case GE     -> emitBinary(v, ">=",        Boolean.TYPE);
      case CMP    -> emitBinary(v, "<=>",       Object.class);
      case BITAND -> emitBinary(v, "`&",        Object.class);
      case BITOR  -> emitBinary(v, "`|",        Object.class);
      case XOR    -> emitBinary(v, "`^",        Object.class);
      case SHL    -> emitBinary(v, "<<",        Object.class);
      case SHR    -> emitBinary(v, ">>",        Object.class);
      case USHR   -> emitBinary(v, ">>>",       Object.class);
      case CAT    -> emitBinary(v, "~",         Object.class);
      case IN     -> emitBinary(v, "<-",        Boolean.TYPE);
      case NEG    -> emitUnary (v, "__neg__",   Object.class);
      case BITNOT -> emitUnary (v, "`!",        Object.class);
      case EMPTY  -> emitUnary (v, "__empty__", Boolean.TYPE);
  
      case IDEQ, IDNE -> {
        InstructionView next = peekNext(v);
        if (next != null && (next.opcode() == JUMP_IF_TRUE ||
                             next.opcode() == JUMP_IF_FALSE)) {
          if ((v.opcode() == IDEQ) ^ (next.opcode() == JUMP_IF_FALSE))
            mc.IF_ACMPEQ(blockLabels[next.jumpTarget()]);
          else
            mc.IF_ACMPNE(blockLabels[next.jumpTarget()]);
          v.advance();
        } else {
          Label t = new Label(), e = new Label();
          if (v.opcode() == IDEQ)
            mc.IF_ACMPEQ(t);
          else
            mc.IF_ACMPNE(t);
          mc.FALSE()
            .GOTO(e)
            .label(t)
            .TRUE()
            .label(e)
            .BOX(Boolean.TYPE);
        }
      }
  
      case INSTANCEOF -> {
        Object cls = fn.getConstant(v.poolIndex());
        if (cls instanceof IRClass irc)
          mc.INSTANCEOF(irc.internalName);
        else
          mc.INSTANCEOF((Class<?>)cls);
        emitJumpAfterCond(v);
      }
  
      case NOT -> {
        InstructionView next = peekNext(v);
        if (next != null && (next.opcode() == JUMP_IF_TRUE ||
                             next.opcode() == JUMP_IF_FALSE)) {
          mc.UNBOX(Boolean.TYPE);
          if (next.opcode() == JUMP_IF_TRUE)
            mc.IFEQ(blockLabels[next.jumpTarget()]);
          else
            mc.IFNE(blockLabels[next.jumpTarget()]);
          v.advance();
        } else {
          mc.UNBOX(Boolean.TYPE)
            .ICONST_1()
            .IXOR()
            .BOX(Boolean.TYPE);
        }
      }

      case PUSH_IND ->
        mc.XLOAD(SLOT(v.payload()), (Class<?>)fn.getConstant(v.poolIndex()));
      case STORE_IND ->
        mc.XSTORE(SLOT(v.payload()), (Class<?>)fn.getConstant(v.poolIndex()));
      case INC_IND ->
        mc.IINC(SLOT(v.payload()), (int)fn.getConstant(v.poolIndex()));

      case JUMP ->
        mc.GOTO(blockLabels[v.jumpTarget()]);
      case JUMP_IF_TRUE ->
        mc.UNBOX(Boolean.TYPE).IFNE(blockLabels[v.jumpTarget()]);
      case JUMP_IF_FALSE ->
        mc.UNBOX(Boolean.TYPE).IFEQ(blockLabels[v.jumpTarget()]);
      case JUMP_IF_NULL ->
        mc.IFNULL(blockLabels[v.jumpTarget()]);
      case JUMP_IF_NONNULL ->
        mc.IFNONNULL(blockLabels[v.jumpTarget()]);

      case RETURN -> {
        if (returnType == Object.class) {
          mc.ARETURN();
        } else if (returnType == Void.TYPE) {
          mc.POP().RETURN();
        } else {
          emitCoerce(returnType);
          mc.XRETURN(returnType);
        }
      }
  
      case THROW ->
        mc.ALOAD(S_CTX())
          .INVOKESTATIC(Runtime.class, "wrapException", Throwable.class,
                        Object.class, ELContext.class)
          .ATHROW();

      case THROW_EXCEPTION -> {
        if (v.count() != 0) {
          String message = (String)fn.getConstant(v.poolIndex());
          mc.NEW(UserException.class)
            .DUP()
            .ALOAD(S_CTX())
            .LDC(message)
            .INVOKESPECIAL(UserException.class, "<init>", Void.TYPE,
                           ELContext.class, String.class)
            .ATHROW();
        } else {
          mc.ATHROW();
        }
      }

      case TRY -> {
        // try {
        // TryStart:
        //     result = body(ctx, []);
        // TryEnd:
        //     if (finalizer != null)
        //         finalizer(ctx, [])
        //     goto done
        // CatchStart:
        // } catch (Throwable caught) {
        //     if (typecheck(type[i], caught)) {
        //         result = handler[i](ctx, [caught])
        //         goto CatchEnd
        //     }
        //     throw caught
        // CatchEnd:
        //     if (finalizer != null)
        //         finalizer(ctx, [])
        //     goto done
        // FinalStart:
        // } finally (caught) {
        //     if (finalizer != null)
        //         finalizer(ctx, [])
        //     throw caught
        // }
        // done:
        //
        // Try-Catch: TryStart, TryEnd, CatchStart, Throwable
        // Try-Catch: TryStart, TryEnd, FinalStart, any
        // Try-Catch: CatchStart, CatchEnd, FinalStart, any

        var desc = (Descriptors.Try)fn.getConstant(v.poolIndex());
        int tmp = TMP_SLOT();
        int resultSlot = tmp++, caughtSlot = tmp;

        Label tryStart = new Label(), tryEnd = new Label();
        Label catchStart = null, catchEnd = null;
        Label finallyStart = null;
        Label done = new Label();

        mc.label(tryStart);
        emitDirectCall(desc.body());
        mc.ASTORE(resultSlot);
        mc.label(tryEnd);
        if (desc.finalizer() != null) {
          emitDirectCall(desc.finalizer());
          mc.POP();
        }
        mc.GOTO(done);

        if (desc.handlers().length != 0) {
          boolean catchAll = false;
          catchStart = new Label();
          catchEnd = new Label();

          mc.label(catchStart);
          mc.ASTORE(caughtSlot);

          for (int i = 0; i < desc.handlers().length; i++) {
            if (desc.types()[i] != null) {
              Label next = new Label();
              mc.ALOAD(caughtSlot)
                .INSTANCEOF(desc.types()[i])
                .IFEQ(next);
              emitDirectCall(desc.handlers()[i], caughtSlot);
              mc.ASTORE(resultSlot);
              mc.GOTO(catchEnd);
              mc.label(next);
            } else {
              emitDirectCall(desc.handlers()[i], caughtSlot);
              mc.ASTORE(resultSlot);
              catchAll = true;
              break;
            }
          }

          // Rethrow if no handler match
          if (!catchAll)
            mc.ALOAD(caughtSlot).ATHROW();

          mc.label(catchEnd);
          if (desc.finalizer() != null) {
            emitDirectCall(desc.finalizer());
            mc.POP();
          }
          mc.GOTO(done);
        }

        // finally { finalizer(ctx, []) }
        if (desc.finalizer() != null) {
          mc.label(finallyStart = new Label());
          emitDirectCall(desc.finalizer());
          mc.POP();
          mc.ATHROW();
        }

        mc.label(done)
          .ALOAD(resultSlot);
  
        if (desc.handlers().length != 0) {
          mc.TryCatchBlock(tryStart, tryEnd, catchStart, Throwable.class);
          if (finallyStart != null) {
            mc.TryCatchBlock(tryStart, tryEnd, finallyStart, (String)null);
            mc.TryCatchBlock(catchStart, catchEnd, finallyStart, (String)null);
          }
        } else {
          assert finallyStart != null;
          mc.TryCatchBlock(tryStart, tryEnd, finallyStart, (String)null);
        }
      }
  
      case SYNCHRONIZED -> {
        IRFunction body = (IRFunction)fn.getConstant(v.poolIndex());
        int tmp = TMP_SLOT();
        int lockSlot = tmp++, resultSlot = tmp;
        Label tryStart = new Label(), tryEnd = new Label();
        Label catchAll = new Label(), done = new Label();
  
        mc.DUP()
          .ASTORE(lockSlot)
          .MONITORENTER();
        mc.label(tryStart);
        emitDirectCall(body);
        mc.ASTORE(resultSlot)
          .ALOAD(lockSlot)
          .MONITOREXIT()
        .label(tryEnd)
          .GOTO(done)
        .label(catchAll)
          .ALOAD(lockSlot)
          .MONITOREXIT()
          .ATHROW()
        .label(done)
          .ALOAD(resultSlot)
        .TryCatchBlock(tryStart, tryEnd, catchAll, Throwable.class);
      }
  
      case ASSERT -> {
        // TODO: create $assertionsDisabled field.
        Label c = new Label();
        if (v.count() == 1) {
          mc.UNBOX(Boolean.TYPE)
            .IFNE(c)
            .NEW(AssertionError.class)
            .DUP()
            .INVOKESPECIAL(AssertionError.class, "<init>", Void.TYPE)
            .ATHROW()
            .label(c)
            .ACONST_NULL();
        } else {
          int tmpSlot = TMP_SLOT();
          mc.SWAP()
            .UNBOX(Boolean.TYPE)
            .IFNE(c)
            .ASTORE(tmpSlot)
            .NEW(AssertionError.class)
            .DUP()
            .ALOAD(tmpSlot)
            .INVOKESPECIAL(AssertionError.class, "<init>", Void.TYPE,
                           Object.class)
            .ATHROW()
            .label(c)
            .POP()
            .ACONST_NULL();
        }
      }
  
      case ENTER_SCOPE ->
        mc.ALOAD(S_ENV())
          .INVOKEVIRTUAL(EvaluationContext.class, "pushContext",
                         EvaluationContext.class)
          .ASTORE(S_ENV());
  
      case LEAVE_SCOPE ->
        mc.ALOAD(S_ENV())
          .INVOKEVIRTUAL(EvaluationContext.class, "popContext",
                         EvaluationContext.class)
          .ASTORE(S_ENV());
  
      case CLOSURE -> {
        IRFunction closure = (IRFunction)fn.getConstant(v.poolIndex());
        String closureName = compileClosure(closure);
        mc.NEW(closureName)
          .DUP()
          .ALOAD(S_ENV());
        if (closure.owner() != null && !closure.isStatic()) {
          IRClass currentClass = fn.owner();
          mc.THIS();
          while (currentClass != closure.owner()) {
            mc.GETFIELD(currentClass.internalName, "$outer",
              AsmType.toDescriptor(currentClass.outer.internalName));
            currentClass = currentClass.outer;
          }
          mc.INVOKESPECIAL(closureName, "<init>", AsmType.toMethodDescriptor(
            "V", EvaluationContext.class.getName(),
            closure.owner().internalName));
        } else {
          mc.INVOKESPECIAL(closureName, "<init>", Void.TYPE,
                           EvaluationContext.class);
        }
      }
  
      case INVOKE_DIRECT -> {
        // Invoke function method, the argument list is on stack top.
        IRFunction f = (IRFunction)fn.getConstant(v.poolIndex());
        String ownerName = f.owner() != null ? f.owner().internalName
                                             : currentClassName;
        if (f.isStatic()) {
          mc.INVOKESTATIC(ownerName, f.internalName, Object.class,
                          EvaluationContext.class, Object[].class);
        } else {
          mc.INVOKEVIRTUAL(ownerName, f.internalName, Object.class,
                           EvaluationContext.class, Object[].class);
        }
      }

      case INVOKE_METHOD -> {
        Method m = (Method)fn.getConstant(v.poolIndex());
        if (Modifier.isStatic(m.getModifiers())) {
          mc.INVOKESTATIC(m.getDeclaringClass(), m.getName(), m.getReturnType(),
                          m.getParameterTypes());
        } else if (m.getDeclaringClass().isInterface()) {
          mc.INVOKEINTERFACE(m.getDeclaringClass(), m.getName(),
                             m.getReturnType(), m.getParameterTypes());
        } else {
          mc.INVOKEVIRTUAL(m.getDeclaringClass(), m.getName(), m.getReturnType(),
                           m.getParameterTypes());
        }

        if (m.getReturnType() == Boolean.TYPE) {
          emitJumpAfterCond(v);
        } else if (m.getReturnType().isPrimitive() &&
                   m.getReturnType() != Void.TYPE) {
          InstructionView next = peekNext(v);
          if (next != null && next.opcode() == UNBOX) {
            v.advance();
          } else if (next != null && next.opcode() == POP) {
            if (m.getReturnType() == long.class ||
                m.getReturnType() == double.class) {
              mc.POP2();
            } else {
              mc.POP();
            }
            v.advance();
          } else {
            mc.BOX(m.getReturnType());
          }
        }
      }

      case INVOKE_DYNAMIC -> {
        var desc = (Descriptors.Indy)fn.getConstant(v.poolIndex());
        Handle handle = new Handle(
          Opcodes.H_INVOKESTATIC,
          AsmType.toInternalName(desc.bootstrap().getDeclaringClass()),
          desc.bootstrap().getName(),
          AsmType.getMethodDescriptor(desc.bootstrap()),
          false);
        Object[] args = Arrays.copyOf(desc.args(), desc.args().length);
        for (int i = 0; i < args.length; i++) {
          if (args[i] instanceof Class)
            args[i] = Type.getType((Class<?>)args[i]);
        }
        mc.INVOKEDYNAMIC(handle, desc.name(),
                         AsmType.getMethodDescriptor(desc.rtype(), desc.ptypes()),
                         args);
      }

      case NEW -> {
        Object cls = fn.getConstant(v.poolIndex());
        if (cls instanceof IRClass irc) {
          mc.NEW(irc.internalName).DUP();
        } else {
          mc.NEW((Class<?>)cls).DUP();
        }
      }

      case CONSTRUCTOR -> {
        Object c = fn.getConstant(v.poolIndex());
        if (c instanceof IRClass irc) {
          if (irc.outer != null) {
            mc.THIS();
            mc.INVOKESPECIAL(irc.internalName, "<init>",
              "(" + AsmType.getDescriptor(EvaluationContext.class) +
              AsmType.getDescriptor(Object[].class) +
              AsmType.toDescriptor(irc.outer.internalName) + ")V");
          } else {
            mc.INVOKESPECIAL(irc.internalName, "<init>", Void.TYPE,
                             EvaluationContext.class, Object[].class);
          }
        } else if (c instanceof Class<?>) {
          emitSuperConstructor((Class<?>)c, v.count());
        } else if (c instanceof Constructor<?> cons) {
          mc.INVOKESPECIAL(cons.getDeclaringClass(), "<init>", Void.TYPE,
                           cons.getParameterTypes());
        }
      }

      case NEW_ARRAY ->
        mc.NEWARRAY((Class<?>)fn.getConstant(v.poolIndex()));

      case NEW_FIXED_ARRAY -> {
        mc.PUSH(v.payload());
        mc.NEWARRAY((Class<?>)fn.getConstant(v.poolIndex()));
      }

      case NEW_MULTI_ARRAY -> {
        Class<?> type = (Class<?>)fn.getConstant(v.poolIndex());
        Object array = Array.newInstance(type, new int[v.payload()]);
        mc.MULTIANEWARRAY(array.getClass(), v.payload());
      }

      case LOAD_ARRAY -> {
        mc.PUSH(v.payload());
        mc.XALOAD((Class<?>)fn.getConstant(v.poolIndex()));
      }
  
      case STORE_ARRAY -> {
        Class<?> c = (Class<?>)fn.getConstant(v.poolIndex());
        emitCoerce(c);
        mc.PUSH(v.payload());
        mc.SWAP();
        mc.XASTORE(c);
      }
  
      case GETFIELD -> {
        Object field = fn.getConstant(v.poolIndex());
        if (field instanceof Descriptors.Field f) {
          if (f.field().equals("$outer")) {
            mc.GETFIELD(f.clazz().internalName, f.field(),
                        AsmType.toDescriptor(f.clazz().outer.internalName));
          } else {
            mc.GETFIELD(f.clazz().internalName, f.field(), Object.class);
          }
        } else if (field instanceof Field f) {
          mc.GETFIELD(f.getDeclaringClass(), f.getName(), f.getType());
          if (f.getType().isPrimitive())
            mc.BOX(f.getType());
        } else {
          mc.THIS().GETFIELD(currentClassName, (String)field, Object.class);
        }
      }
  
      case PUTFIELD -> {
        Object field = fn.getConstant(v.poolIndex());
        String className, fieldName;
        Class<?> type;

        if (field instanceof Descriptors.Field f) {
          className = f.clazz().internalName;
          fieldName = f.field();
          type = Object.class;
          mc.SWAP();
        } else if (field instanceof Field f) {
          className = f.getDeclaringClass().getName();
          fieldName = f.getName();
          type = f.getType();
          mc.SWAP();
        } else {
          className = currentClassName;
          fieldName = (String)field;
          type = Object.class;
          mc.THIS().SWAP();
        }

        InstructionView next = peekNext(v);
        if (next == null || next.opcode() != POP)
          mc.DUP_X1();
        else
          v.advance(); // no DUP, eat POP
        if (type.isPrimitive())
          mc.UNBOX_UNCHECKED(type);
        mc.PUTFIELD(className, fieldName, type);
      }
  
      case GETSTATIC -> {
        Object field = fn.getConstant(v.poolIndex());
        if (field instanceof Descriptors.Field f) {
          mc.GETSTATIC(f.clazz().internalName, f.field(), Object.class);
        } else if (field instanceof Field f) {
          mc.GETSTATIC(f.getDeclaringClass(), f.getName(), f.getType());
          if (f.getType().isPrimitive())
            mc.BOX(f.getType());
        } else {
          mc.GETSTATIC(currentClassName, (String)field, Object.class);
        }
      }
  
      case PUTSTATIC -> {
        Object field = fn.getConstant(v.poolIndex());
        String className, fieldName;
        Class<?> type;

        if (field instanceof Descriptors.Field f) {
          className = f.clazz().internalName;
          fieldName = f.field();
          type = Object.class;
        } else if (field instanceof Field f) {
          className = f.getDeclaringClass().getName();
          fieldName = f.getName();
          type = f.getType();
          emitCoerce(TypeCoercion.getBoxedType(type));
        } else {
          className = currentClassName;
          fieldName = (String)field;
          type = Object.class;
        }

        InstructionView next = peekNext(v);
        if (next == null || next.opcode() != POP)
          mc.DUP();
        else
          v.advance(); // no DUP, eat POP
        if (type.isPrimitive())
          mc.UNBOX_UNCHECKED(type);
        mc.PUTSTATIC(className, fieldName, type);
      }
  
      case CHECKCAST -> {
        Object cls = fn.getConstant(v.poolIndex());
        if (cls instanceof IRClass)
          mc.CHECKCAST(((IRClass)cls).internalName);
        else
          mc.CHECKCAST((Class<?>)cls);
      }

      case BOX ->
        mc.BOX((Class<?>)fn.getConstant(v.poolIndex()));
      case UNBOX ->
        mc.UNBOX((Class<?>)fn.getConstant(v.poolIndex()));

      case NEW_TUPLE -> {
        int cnt = v.count();
        mc.PUSH(cnt);
        mc.ANEWARRAY(Object.class);
        for (int i = cnt; i != 0; i--) {
          mc.DUP_X1()
            .SWAP()
            .PUSH(i - 1)
            .SWAP()
            .AASTORE();
        }
      }
  
      case DECLARE_NS -> {
        emitCoerce(String.class);
        mc.ALOAD(S_ENV())
          .SWAP()
          .LDC(fn.getConstant(v.poolIndex()))
          .SWAP()
          .INVOKEVIRTUAL(EvaluationContext.class, "declarePrefix", Void.TYPE,
                         String.class, String.class);
      }

      default -> throw new CompilationError(
        _T(IR_BC_UNHANDLED_OPCODE, v.opcode(), Opcode.name(v.opcode())));
      }
    }

    private String compileClosure(IRFunction closure) {
      String name = getClosureName(closure);
      if (createdClosures.contains(closure))
        return name;

      ClassAssembly cc = new ClassAssembly(ACC_PRIVATE | ACC_SUPER, name,
                                           IRCompiledClosure.class, null);
      attachSource(cc, closure.debugInfo());

      MethodAssembly mc;
      if (closure.owner() != null && !closure.isStatic()) {
        String ownerName = closure.owner().internalName;
        cc.addField(ACC_PRIVATE, "$this", AsmType.toDescriptor(ownerName));
        mc = cc.newMethod(ACC_PUBLIC, "<init>", AsmType.toMethodDescriptor(
          "V", EvaluationContext.class.getName(), ownerName), null);
        mc.THIS()
          .ALOAD(2)
          .PUTFIELD(name, "$this", AsmType.toDescriptor(ownerName));
      } else {
        mc = cc.newMethod(ACC_PUBLIC, "<init>", Void.TYPE,
                          EvaluationContext.class);
      }

      // Constructor.
      mc.THIS()
        .ALOAD(1)
        .INVOKESPECIAL(IRCompiledClosure.class, "<init>", Void.TYPE,
                       EvaluationContext.class)
        .RETURN()
        .end();

      // Arity, returns the number of parameters.
      cc.newMethod(ACC_PUBLIC, "arity", int.class, ELContext.class)
        .PUSH(closure.paramCount())
        .IRETURN()
        .end();

      // The main execution entry point. Delegate to actual closure method.
      mc = cc.newMethod(ACC_PROTECTED, "execute", Object.class,
                        EvaluationContext.class, Object[].class);
      String ownerName = closure.owner() != null ? closure.owner().internalName
                                                 : currentClassName;
      if (closure.owner() != null && !closure.isStatic()) {
        mc.THIS()
          .GETFIELD(name, "$this", AsmType.toDescriptor(ownerName))
          .ALOAD(1)
          .INVOKEVIRTUAL(EvaluationContext.class, "pushContext",
                         EvaluationContext.class)
          .DUP()
          .INVOKEVIRTUAL(EvaluationContext.class, "getELContext",
                         ELContext.class)
          .PUSH(closure.paramCount())
          .LDC(Type.getType(AsmType.toDescriptor(ownerName)))
          .LDC(closure.internalName)
          .ALOAD(2)
          .INVOKESTATIC(IRCompiledClosure.class, "getArgs", Object[].class,
                        ELContext.class, int.class, Class.class, String.class,
                        Object[].class)
          .INVOKEVIRTUAL(ownerName, closure.internalName, Object.class,
                         EvaluationContext.class, Object[].class)
          .ARETURN()
          .end();
      } else {
        mc.ALOAD(1)
          .INVOKEVIRTUAL(EvaluationContext.class, "pushContext",
                         EvaluationContext.class)
          .DUP()
          .INVOKEVIRTUAL(EvaluationContext.class, "getELContext",
                         ELContext.class)
          .PUSH(closure.paramCount())
          .LDC(Type.getType(AsmType.toDescriptor(ownerName)))
          .LDC(closure.internalName)
          .ALOAD(2)
          .INVOKESTATIC(IRCompiledClosure.class, "getArgs", Object[].class,
                          ELContext.class, int.class, Class.class, String.class,
                          Object[].class)
          .INVOKESTATIC(ownerName, closure.internalName, Object.class,
                        EvaluationContext.class, Object[].class)
          .ARETURN()
          .end();
      }

      // toString
      mc = cc.newMethod(ACC_PUBLIC, "toString", String.class);
      if (closure.name() == null || closure.name().equals("<lambda>"))
        mc.LDC("#<procedure>");
      else
        mc.LDC("#<procedure: " + closure.name() + ">");
      mc.ARETURN();
      mc.end();

      createdClosures.add(closure);
      consumer.acceptClass(name, cc.end());
      return name;
    }

    private static final Handle RESOLVE_CONSTRUCTOR_BOOTSTRAP =
      new Handle(
        Opcodes.H_INVOKESTATIC, AsmType.toInternalName(DynamicBootstrap.class),
        "resolveConstructorBootstrap",
        AsmType.getMethodDescriptor(CallSite.class, MethodHandles.Lookup.class,
                                    String.class, MethodType.class, Class.class),
        false);

    private void emitSuperConstructor(Class<?> baseClass, int arity) {
      List<Constructor<?>> constructors = new ArrayList<>();
      for (Constructor<?> c : baseClass.getDeclaredConstructors()) {
        if (c.getParameterCount() == arity &&
            (Modifier.isPublic(c.getModifiers()) ||
             Modifier.isProtected(c.getModifiers())))
          constructors.add(c);
      }
      assert constructors.size() > 1;

      Label[] labels = new Label[constructors.size()];
      for (int i = 0; i < labels.length; i++)
        labels[i] = new Label();
      Label dflt = new Label(), done = new Label();

      int argsSlot = TMP_SLOT();
      mc.ASTORE(argsSlot);

      mc.ALOAD(argsSlot)
        .INVOKEDYNAMIC(RESOLVE_CONSTRUCTOR_BOOTSTRAP, "super",
                       AsmType.getMethodDescriptor(int.class, Object[].class),
                       Type.getType(baseClass))
        .TABLESWITCH(0, constructors.size() - 1, labels, dflt);

      for (int i = 0; i < constructors.size(); i++) {
        Constructor<?> cons = constructors.get(i);
        Class<?>[] types = cons.getParameterTypes();
        mc.label(labels[i]);
        mc.THIS();
        for (int j = 0; j < types.length; j++) {
          if (types[j] == Object.class) {
            mc.ALOAD(argsSlot)
              .PUSH(j)
              .AALOAD();
          } else {
            mc.ALOAD(S_CTX())
              .ALOAD(argsSlot)
              .PUSH(j)
              .AALOAD()
              .INVOKEDYNAMIC(COERCE_BOOTSTRAP, "coerce",
                             AsmType.getMethodDescriptor(
                               types[j], ELContext.class, Object.class));
          }
        }
        mc.INVOKESPECIAL(baseClass, "<init>", void.class, types);
        mc.GOTO(done);
      }

      mc.label(dflt)
        .NEW(EvaluationException.class)
        .DUP()
        .ALOAD(S_CTX())
        .GETSTATIC(Resources.class, EL_CONSTRUCTOR_NOT_FOUND, String.class)
        .ICONST_1()
        .ANEWARRAY(Object.class)
        .DUP()
        .ICONST_0()
        .LDC(baseClass.getName())
        .AASTORE()
        .INVOKESTATIC(Resources.class, "getText", String.class, String.class,
                      Object[].class)
        .INVOKESPECIAL(EvaluationException.class, "<init>", void.class,
                       ELContext.class, String.class)
        .ATHROW();

      mc.label(done);
    }

    private InstructionView peekNext(InstructionView v) {
      InstructionView next = v.peek();
      if (next.inBounds() && fn.blockOfPc(next.offset()) == -1)
        return next;
      return null;
    }

    private static final Handle COERCE_BOOTSTRAP =
      new Handle(
        Opcodes.H_INVOKESTATIC, AsmType.toInternalName(CoercionBootstrap.class),
        "coerceBootstrap",
        AsmType.getMethodDescriptor(CallSite.class, MethodHandles.Lookup.class,
                                    String.class, MethodType.class),
        false);

    private static final Handle BINARY_BOOTSTRAP =
      new Handle(
        Opcodes.H_INVOKESTATIC, AsmType.toInternalName(OperatorBootstrap.class),
        "binaryBootstrap",
        AsmType.getMethodDescriptor(CallSite.class, MethodHandles.Lookup.class,
                                    String.class, MethodType.class),
        false);

    private static final Handle UNARY_BOOTSTRAP =
      new Handle(
        Opcodes.H_INVOKESTATIC, AsmType.toInternalName(OperatorBootstrap.class),
        "unaryBootstrap",
        AsmType.getMethodDescriptor(CallSite.class, MethodHandles.Lookup.class,
                                    String.class, MethodType.class),
        false);

    private void emitPushPrimitive(InstructionView v, Object value) {
      InstructionView next = peekNext(v);
      if (next == null) {
        mc.BOX(value);
        return;
      }

      switch (next.opcode()) {
      case UNBOX: {
        Class<?> unboxedType = (Class<?>)fn.getConstant(next.poolIndex());
        if (value.getClass() == TypeCoercion.getBoxedType(unboxedType)) {
          mc.PUSH_CONST(value);
          v.advance();
          return;
        }
        break;
      }

      case RETURN: {
        if (returnType == void.class) {
          mc.RETURN();
          v.advance();
          return;
        }
        if (returnType.isPrimitive()) {
          mc.PUSH_CONST(value);
          emitPrimitiveConversion(value, returnType);
          mc.XRETURN(returnType);
          v.advance();
          return;
        }
        break;
      }

      case STORE_ARRAY: {
        Class<?> arrayType = (Class<?>)fn.getConstant(next.poolIndex());
        if (arrayType.isPrimitive()) {
          mc.PUSH(next.payload());
          mc.PUSH_CONST(value);
          emitPrimitiveConversion(value, arrayType);
          mc.XASTORE(arrayType);
          v.advance();
          return;
        }
        break;
      }
      }

      mc.BOX(value);
    }

    private void emitPrimitiveConversion(Object value, Class<?> type) {
      if (type == boolean.class || type == byte.class || type == short.class ||
          type == char.class || type == int.class) {
        if (value instanceof Long)
          mc.L2I();
        else if (value instanceof Float)
          mc.F2I();
        else if (value instanceof Double)
          mc.D2I();
      } else if (type == long.class && !(value instanceof Long)) {
        if (value instanceof Float)
          mc.F2L();
        else if (value instanceof Double)
          mc.D2L();
        else
          mc.I2L();
      } else if (type == float.class && !(value instanceof Float)) {
        if (value instanceof Double)
          mc.D2F();
        else if (value instanceof Long)
          mc.L2F();
        else
          mc.I2F();
      } else if (type == double.class && !(value instanceof Double)) {
        if (value instanceof Long)
          mc.L2D();
        else if (value instanceof Float)
          mc.F2D();
        else
          mc.I2D();
      }
    }

    private void emitPushString(InstructionView v, String value) {
      InstructionView next = peekNext(v);
      if (next != null && next.opcode() == STORE_ARRAY) {
        Class<?> arrayType = (Class<?>)fn.getConstant(next.poolIndex());
        if (arrayType == String.class || arrayType == Object.class) {
          mc.PUSH(next.payload());
          mc.LDC(value);
          mc.AASTORE();
          v.advance();
          return;
        }
      }

      mc.LDC(value);
    }

    private void emitCoerce(Class<?> type) {
      if (type != Object.class) {
        mc.ALOAD(S_CTX());
        mc.SWAP();
        mc.INVOKEDYNAMIC(COERCE_BOOTSTRAP, "coerce",
                         AsmType.getMethodDescriptor(
                           type, ELContext.class, Object.class));
      }
    }

    private void emitBinary(InstructionView v, String name, Class<?> returnType) {
      if (v.payload() == IRFormat.K_DYNAMIC) {
        mc.ALOAD(S_ENV());
        mc.INVOKEDYNAMIC(BINARY_BOOTSTRAP, mangle(name),
          AsmType.getMethodDescriptor(returnType, Object.class, Object.class,
                                      EvaluationContext.class));
        if (returnType == Boolean.TYPE)
          emitJumpAfterCond(v);
      } else {
        emitBuiltinBinary(v, returnType);
      }
    }

    private void emitBuiltinBinary(InstructionView v, Class<?> returnType) {
      if (returnType == boolean.class) {
        InstructionView next = peekNext(v);
        if (next != null && (next.opcode() == JUMP_IF_TRUE ||
                             next.opcode() == JUMP_IF_FALSE)) {
          int opcode = v.opcode();
          if (next.opcode() == JUMP_IF_FALSE) {
            opcode = switch (opcode) {
              case EQ -> NE;
              case NE -> EQ;
              case LT -> GE;
              case LE -> GT;
              case GT -> LE;
              case GE -> LT;
              default -> throw new AssertionError();
            };
          }
          emitCompare(opcode, v.payload(), blockLabels[next.jumpTarget()]);
          v.advance();
        } else {
          Label t = new Label(), e = new Label();
          emitCompare(v.opcode(), v.payload(), t);
          mc.FALSE()
            .GOTO(e)
            .label(t)
            .TRUE()
            .label(e);
        }
        return;
      }

      if (v.payload() == IRFormat.K_INT) {
        switch (v.opcode()) {
        case ADD    -> mc.IADD();
        case SUB    -> mc.ISUB();
        case MUL    -> mc.IMUL();
        case IDIV   -> mc.IDIV();
        case REM    -> mc.IREM();
        case BITAND -> mc.IAND();
        case BITOR  -> mc.IOR();
        case XOR    -> mc.IXOR();
        case SHL    -> mc.ISHL();
        case SHR    -> mc.ISHR();
        case USHR   -> mc.IUSHR();
        default     -> throw new AssertionError();
        }
        return;
      }

      if (v.payload() == IRFormat.K_LONG) {
        switch (v.opcode()) {
        case ADD    -> mc.LADD();
        case SUB    -> mc.LSUB();
        case MUL    -> mc.LMUL();
        case IDIV   -> mc.LDIV();
        case REM    -> mc.LREM();
        case BITAND -> mc.LAND();
        case BITOR  -> mc.LOR();
        case XOR    -> mc.LXOR();
        case SHL    -> mc.LSHL();
        case SHR    -> mc.LSHR();
        case USHR   -> mc.LUSHR();
        default     -> throw new AssertionError();
        }
        return;
      }

      if (v.payload() == IRFormat.K_FLOAT) {
        switch (v.opcode()) {
        case ADD -> mc.FADD();
        case SUB -> mc.FSUB();
        case MUL -> mc.FMUL();
        case DIV -> mc.FDIV();
        case REM -> mc.FREM();
        default  -> throw new AssertionError();
        }
        return;
      }

      if (v.payload() == IRFormat.K_DOUBLE) {
        switch (v.opcode()) {
        case ADD -> mc.DADD();
        case SUB -> mc.DSUB();
        case MUL -> mc.DMUL();
        case DIV -> mc.DDIV();
        case REM -> mc.DREM();
        default  -> throw new AssertionError();
        }
        return;
      }

      if (v.payload() == IRFormat.K_BOOL) {
        switch (v.opcode()) {
        case BITAND -> mc.IAND();
        case BITOR  -> mc.IOR();
        case XOR    -> mc.IXOR();
        default     -> throw new AssertionError();
        }
        return;
      }

      throw new AssertionError("Not yet implemented");
    }

    private void emitCompare(int opcode, int kind, Label target) {
      if (kind == IRFormat.K_INT || kind == IRFormat.K_BOOL) {
        switch (opcode) {
        case EQ -> mc.IF_ICMPEQ(target);
        case NE -> mc.IF_ICMPNE(target);
        case LT -> mc.IF_ICMPLT(target);
        case LE -> mc.IF_ICMPLE(target);
        case GT -> mc.IF_ICMPGT(target);
        case GE -> mc.IF_ICMPGE(target);
        default -> throw new AssertionError();
        }
      } else {
        if (kind == IRFormat.K_LONG)
          mc.LCMP();
        else if (kind == IRFormat.K_FLOAT)
          mc.FCMPL();
        else if (kind == IRFormat.K_DOUBLE)
          mc.DCMPL();
        else
          throw new AssertionError();

        switch (opcode) {
        case EQ -> mc.IFEQ(target);
        case NE -> mc.IFNE(target);
        case LT -> mc.IFLT(target);
        case LE -> mc.IFLE(target);
        case GT -> mc.IFGT(target);
        case GE -> mc.IFGE(target);
        default -> throw new AssertionError();
        }
      }
    }

    private void emitUnary(InstructionView v, String name, Class<?> returnType) {
      mc.ALOAD(S_ENV());
      mc.INVOKEDYNAMIC(UNARY_BOOTSTRAP, mangle(name),
        AsmType.getMethodDescriptor(returnType, Object.class,
                                    EvaluationContext.class));
      if (returnType == Boolean.TYPE)
        emitJumpAfterCond(v);
    }

    private void emitJumpAfterCond(InstructionView v) {
      InstructionView next = peekNext(v);
      if (next != null && (next.opcode() == JUMP_IF_TRUE ||
                           next.opcode() == JUMP_IF_FALSE)) {
        if (next.opcode() == JUMP_IF_TRUE)
          mc.IFNE(blockLabels[next.jumpTarget()]);
        else
          mc.IFEQ(blockLabels[next.jumpTarget()]);
        v.advance();
      } else {
        mc.BOX(Boolean.TYPE);
      }
    }

    private void emitDirectCall(IRFunction fn) {
      if (!fn.isStatic())
        mc.THIS();
      mc.ALOAD(S_ENV())
        .INVOKEVIRTUAL(EvaluationContext.class, "pushContext",
                       EvaluationContext.class)
        .ACONST_NULL()
        .invoke(fn.isStatic() ? Opcodes.INVOKESTATIC : Opcodes.INVOKEVIRTUAL,
                currentClassName, fn.internalName, Object.class,
                EvaluationContext.class, Object[].class);
    }

    private void emitDirectCall(IRFunction fn, int arg) {
      if (!fn.isStatic())
        mc.THIS();
      mc.ALOAD(S_ENV())
        .INVOKEVIRTUAL(EvaluationContext.class, "pushContext",
                       EvaluationContext.class)
        .ICONST_1()
        .ANEWARRAY(Object.class)
        .DUP()
        .ICONST_0()
        .ALOAD(arg)
        .AASTORE()
        .invoke(fn.isStatic() ? Opcodes.INVOKESTATIC : Opcodes.INVOKEVIRTUAL,
                currentClassName, fn.internalName, Object.class,
                EvaluationContext.class, Object[].class);
    }
  }

  //----------------------------------------------------------------------------

  private static class JITBytecodeConsumer implements BytecodeConsumer {
    private final DynamicClassLoader loader;
    private Class<?> programClass;

    JITBytecodeConsumer(DynamicClassLoader loader) {
      this.loader = loader;
    }

    @Override
    public void acceptProgram(String className, byte[] bytecode) {
      programClass = loader.addClass(className, bytecode);
    }

    @Override
    public void acceptClass(String className, byte[] bytecode) {
      loader.addClass(className, bytecode);
    }

    IRCompiledFunction complete() {
      try {
        MethodHandles.Lookup lookup = MethodHandles.lookup();
        MethodHandle target = lookup.findStatic(
          programClass, "fn$main", MethodType.methodType(
            Object.class, EvaluationContext.class, Object[].class));
        return new IRCompiledFunction(target);
      } catch (NoSuchMethodException | IllegalAccessException e) {
        throw new RuntimeException(_T(IR_BYTECODE_COMPILE_FAILED), e);
      }
    }
  }
}
