package org.elite.ir;

import org.elite.eval.ELEngine;
import org.elite.eval.EvaluationContext;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;

import javax.el.ELContext;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class IRCompiledFunction {

  private final Method method;
  private final byte[] bytecode;

  IRCompiledFunction(Method m, byte[] bc) {
    this.method   = m;
    this.bytecode = bc;
  }

  public byte[] getBytecode() {
    return bytecode;
  }

  public Object execute(ELContext elctx, Object[] args) {
    ELContext previousContext = ELEngine.setCurrentELContext(elctx);
    try {
      EvaluationContext env = new EvaluationContext(elctx);
      return method.invoke(null, env, args);
    } catch (InvocationTargetException e) {
      Throwable cause = e.getCause();
      if (cause instanceof RuntimeException re)
        throw re;
      if (cause instanceof Error err)
        throw err;
      throw new RuntimeException(cause);
    } catch (IllegalAccessException e) {
      throw new RuntimeException(e);
    } finally {
      ELEngine.setCurrentELContext(previousContext);
    }
  }

  /**
   * Return a human-readable disassembly of the generated bytecode.
   */
  public String dump() {
    if (bytecode == null)
      return "[no bytecode]";
    StringWriter sw = new StringWriter();
    PrintWriter pw = new PrintWriter(sw);
    new ClassReader(bytecode).accept(new BytecodePrinter(pw), 0);
    return sw.toString();
  }

  /**
   * Simple ASM ClassVisitor that prints method bytecode.
   */
  private static class BytecodePrinter extends ClassVisitor {
    private final PrintWriter pw;

    BytecodePrinter(PrintWriter pw) {
      super(589824);
      this.pw = pw;
    }

    @Override
    public void visit(int version, int access, String name, String sig,
                      String superName, String[] interfaces) {
      pw.println(name + ":");
    }

    @Override
    public MethodVisitor visitMethod(int access, String name, String desc,
                                     String sig, String[] exceptions) {
      if (name.equals("<init>"))
        return null;
      pw.println("  " + name + desc + ":");
      return new MethodPrinter(pw);
    }
  }

  private static class MethodPrinter extends MethodVisitor {
    private final PrintWriter pw;

    MethodPrinter(PrintWriter pw) {
      super(589824);
      this.pw = pw;
    }

    @Override
    public void visitInsn(int opcode) {
      pw.printf("    %s\n", opcodeName(opcode));
    }

    @Override
    public void visitIntInsn(int opcode, int operand) {
      pw.printf("    %s %d\n", opcodeName(opcode), operand);
    }

    @Override
    public void visitVarInsn(int opcode, int varIndex) {
      pw.printf("    %s %d\n", opcodeName(opcode), varIndex);
    }

    @Override
    public void visitTypeInsn(int opcode, String type) {
      pw.printf("    %s %s\n", opcodeName(opcode), type);
    }

    @Override
    public void visitFieldInsn(int opcode, String owner, String name,
                               String desc) {
      pw.printf("    %s %s.%s %s\n", opcodeName(opcode), owner, name, desc);
    }

    @Override
    public void visitMethodInsn(int opcode, String owner, String name,
                                String desc, boolean itf) {
      pw.printf("    %s %s.%s%s\n", opcodeName(opcode), owner, name, desc);
    }

    @Override
    public void visitJumpInsn(int opcode, Label label) {
      pw.printf("    %s L%d\n", opcodeName(opcode),
                System.identityHashCode(label) & 0xFFFF);
    }

    @Override
    public void visitLdcInsn(Object cst) {
      pw.printf("    ldc %s\n", cst);
    }

    @Override
    public void visitLabel(Label label) {
      pw.printf("  L%d:\n", System.identityHashCode(label) & 0xFFFF);
    }

    private static String opcodeName(int op) {
      return switch (op) {
        case 0 -> "nop";
        case 1 -> "aconst_null";
        case 2 -> "iconst_m1";
        case 3 -> "iconst_0";
        case 4 -> "iconst_1";
        case 5 -> "iconst_2";
        case 6 -> "iconst_3";
        case 7 -> "iconst_4";
        case 8 -> "iconst_5";
        case 9 -> "lconst_0";
        case 10 -> "lconst_1";
        case 14 -> "dconst_0";
        case 15 -> "dconst_1";
        case 16 -> "bipush";
        case 17 -> "sipush";
        case 18 -> "ldc";
        case 21 -> "iload";
        case 25 -> "aload";
        case 46 -> "iaload";
        case 50 -> "aaload";
        case 75 -> "astore_0";
        case 76 -> "astore_1";
        case 77 -> "astore_2";
        case 78 -> "astore_3";
        case 58 -> "astore";
        case 79 -> "iastore";
        case 83 -> "aastore";
        case 87 -> "pop";
        case 89 -> "dup";
        case 90 -> "dup_x1";
        case 95 -> "swap";
        case 96 -> "iadd";
        case 100 -> "isub";
        case 104 -> "imul";
        case 108 -> "idiv";
        case 112 -> "irem";
        case 116 -> "ineg";
        case 97 -> "ladd";
        case 101 -> "lsub";
        case 105 -> "lmul";
        case 109 -> "ldiv";
        case 113 -> "lrem";
        case 117 -> "lneg";
        case 99 -> "dadd";
        case 103 -> "dsub";
        case 107 -> "dmul";
        case 111 -> "ddiv";
        case 119 -> "dneg";
        case 148 -> "lcmp";
        case 152 -> "dcmpg";
        case 153 -> "ifeq";
        case 154 -> "ifne";
        case 155 -> "iflt";
        case 156 -> "ifge";
        case 157 -> "ifgt";
        case 158 -> "ifle";
        case 159 -> "if_icmpeq";
        case 160 -> "if_icmpne";
        case 161 -> "if_icmplt";
        case 162 -> "if_icmpge";
        case 163 -> "if_icmpgt";
        case 164 -> "if_icmple";
        case 167 -> "goto";
        case 176 -> "areturn";
        case 177 -> "return";
        case 178 -> "getstatic";
        case 179 -> "putstatic";
        case 182 -> "invokevirtual";
        case 183 -> "invokespecial";
        case 184 -> "invokestatic";
        case 185 -> "invokeinterface";
        case 187 -> "new";
        case 189 -> "anewarray";
        case 192 -> "checkcast";
        case 198 -> "ifnull";
        case 199 -> "ifnonnull";
        default -> "op_" + op;
      };
    }
  }
}
