/*
 * Copyright 2006-2026 Daniel Yuan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package elite.rt;

import javax.el.ELContext;

import elite.lang.Closure;
import elite.lang.Decimal;
import elite.lang.Rational;
import elite.lang.Seq;
import org.operamasks.el.eval.ELEngine;
import org.operamasks.el.eval.TypeCoercion;
import org.operamasks.el.eval.seq.Cons;
import org.operamasks.el.ir.IRClosure;
import org.operamasks.el.ir.IRFormat;
import org.operamasks.el.ir.IRFunction;
import org.operamasks.el.ir.IRInterpreter;
import org.operamasks.el.parser.Token;

import java.lang.reflect.Array;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.MathContext;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Collection;

import static org.operamasks.el.resources.Resources.*;

/**
 * Runtime support methods called from ELite-generated bytecode via {@code invokestatic}.
 */
public final class Runtime {

    private Runtime() {
    }

    // ── ELContext-dependent helpers ──

    public static Object pushGlobal(ELContext c, String name) {
        javax.el.ValueExpression ve = c.getVariableMapper().resolveVariable(name);
        if (ve != null)
            return ve.getValue(c);
        // Check FunctionMapper for global/imported functions
        org.operamasks.el.resolver.MethodResolver mr =
            org.operamasks.el.resolver.MethodResolver.getInstance(c);
        if (mr != null) {
            org.operamasks.el.eval.closure.MethodClosure mc =
                mr.resolveGlobalMethod(c.getFunctionMapper(), name);
            if (mc != null)
                return mc;
        }
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, null, name);
        if (c.isPropertyResolved())
            return r;
        throw new RuntimeException(_T(EL_UNDEFINED_IDENTIFIER, name));
    }

    public static Object storeGlobal(ELContext c, String name, Object value) {
        c.getVariableMapper().setVariable(name, new org.operamasks.el.eval.closure.LiteralClosure(value));
        return value;
    }

    public static Object loadProp(ELContext c, Object base, Object key) {
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, base, key);
        if (!c.isPropertyResolved())
            throw new RuntimeException(_T(EL_PROPERTY_NOT_FOUND, base.getClass().getName(), key));
        return r;
    }

    public static Object storeProp(ELContext c, Object base, Object key, Object value) {
        c.getELResolver().setValue(c, base, key, value);
        return value;
    }

    public static Object trampoline(ELContext c, Object nodeObj) {
        org.operamasks.el.parser.ELNode node = (org.operamasks.el.parser.ELNode) nodeObj;
        return node.getValue(new org.operamasks.el.eval.EvaluationContext(c));
    }

    /** Evaluate a trampoline node by pool index (for bytecode — LDC can't embed ELNode). */
    public static Object trampolineById(ELContext c, int poolIdx) {
        return trampoline(c, funcPool.get()[poolIdx]);
    }

    /** Evaluate a TRY node via AST (using TryDescriptor's original TRY node). */
    public static Object trampolineTry(ELContext c, int poolIdx) {
        Object obj = funcPool.get()[poolIdx];
        if (obj instanceof org.operamasks.el.ir.TryDescriptor td) {
            return trampoline(c, td.tryNode);
        }
        return trampoline(c, obj);
    }

    /**
     * After a TRAMPOLINE causes AST evaluation (which may modify global variables
     * through the VariableMapper), sync those changes back to the local slots
     * so subsequent PUSH_VAR instructions see updated values.
     */
    public static void syncLocals(javax.el.ELContext ctx, Object[] locals, String[] varNames) {
        if (locals == null || varNames == null) return;
        javax.el.VariableMapper vm = ctx.getVariableMapper();
        for (int i = 0; i < varNames.length && i < locals.length; i++) {
            javax.el.ValueExpression ve = vm.resolveVariable(varNames[i]);
            if (ve != null) {
                locals[i] = ve.getValue(ctx);
            }
        }
    }

    /** Wrap a throwable value as RuntimeException for ATHROW bytecode. */
    public static RuntimeException wrapThrow(Object cause) {
        if (cause instanceof RuntimeException re) return re;
        if (cause instanceof Throwable t)
            return new org.operamasks.el.eval.UserException(null, t);
        if (cause instanceof String s)
            return new org.operamasks.el.eval.UserException(null, s);
        return new org.operamasks.el.eval.UserException(null);
    }

    public static Object invokeDyn(ELContext c, Object target, Object[] args) {
        if (target instanceof IRFunction irFn) {
            return new IRInterpreter(c, irFn, null).execute(args);
        }
        if (target instanceof IRClosure closure) {
            IRFunction irFn = closure.getFunction();
            int paramCount = irFn.paramCount();
            int captureCount = irFn.captureCount();
            Object[] expandedArgs = new Object[paramCount + captureCount];
            System.arraycopy(args, 0, expandedArgs, 0, Math.min(args.length, paramCount));
            System.arraycopy(closure.getCaptured(), 0, expandedArgs, paramCount, captureCount);
            return new IRInterpreter(c, irFn, null).execute(expandedArgs);
        }
        Closure[] closures = ELEngine.getCallArgs(args);
        return ELEngine.invokeTarget(c, target, closures);
    }

    // ── Collections ──

    public static Object newList(Object[] elems) {
        return java.util.Arrays.asList(elems);
    }

    /** Reference/identity equality (===). */
    public static Object refEq(Object x, Object y) {
        return x == y;
    }

    /** Reference/identity inequality (!==). */
    public static Object refNe(Object x, Object y) {
        return x != y;
    }

    public static Object newMap(Object[] kvs) {
        java.util.LinkedHashMap<Object, Object> m = new java.util.LinkedHashMap<>();
        for (int i = 0; i < kvs.length; i += 2)
            m.put(kvs[i], kvs[i + 1]);
        return m;
    }

    public static Object newTuple(Object[] elems) {
        return elems;
    }

    public static Object newRange(Object begin, Object end) {
        return org.operamasks.el.eval.Ranges.createRange(
                ((Number)begin).longValue(), ((Number)end).longValue(), 1);
    }

    /** 'in' operator following ELNode.IN.eval() logic. */
    public static Object dynIn(Object coll, Object elem) {
        if (coll == null || elem == null) return false;

        if (coll instanceof Object[] a) {
            for (Object o : a) if (equality(elem, o, true)) return true;
            return false;
        }
        if (coll.getClass().isArray()) {
            int len = java.lang.reflect.Array.getLength(coll);
            Class<?> ct = coll.getClass().getComponentType();
            elem = tryCoerce(null, elem, ct);
            for (int i = 0; i < len; i++) {
                if (equality(elem, java.lang.reflect.Array.get(coll, i), true)) return true;
            }
            return false;
        }
        if (coll instanceof java.util.Collection<?> c) {
            if (elem instanceof java.util.Collection) return c.containsAll((java.util.Collection<?>)elem);
            if (c instanceof java.util.Set || c instanceof elite.lang.Range) return c.contains(elem);
            if (c instanceof Seq seq) {
                while (!seq.isEmpty()) {
                    if (equality(elem, seq.head(), true)) return true;
                    seq = seq.tail();
                }
                return false;
            }
            // Generic collection: iterate with equality comparison
            for (Object o : c) if (equality(elem, o, true)) return true;
            return false;
        }
        return false;
    }

    public static Object getIter(Object coll) {
        return IRInterpreter.getIterator(coll);
    }

    public static Object iterNext(Object it) {
        java.util.Iterator<?> iter = (java.util.Iterator<?>) it;
        return iter.hasNext() ? iter.next() : null;
    }

    // ── Field access ──

    public static Object loadField(Object base, String name) {
        if (base == null)
            throw new NullPointerException(_T(IR_FIELD_READ_FROM_NULL, name));
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            return f.get(target);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(_T(IR_FIELD_NOT_FOUND, name, base.getClass().getName()));
        } catch (IllegalAccessException e) {
            throw new RuntimeException(_T(IR_FIELD_ACCESS_ERROR, name), e);
        }
    }

    public static Object storeFieldBC(Object value, Object base, String name) {
        if (base == null)
            throw new NullPointerException(_T(IR_FIELD_WRITE_TO_NULL, name));
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            f.set(target, coerceArg(value, f.getType()));
            return value;
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(_T(IR_FIELD_NOT_FOUND, name, base.getClass().getName()));
        } catch (IllegalAccessException e) {
            throw new RuntimeException(_T(IR_FIELD_ACCESS_ERROR, name), e);
        }
    }

    private static Object coerceArg(Object arg, Class<?> paramType) {
        if (arg == null || paramType.isInstance(arg)) return arg;
        if (arg instanceof Number n) {
            if (paramType == int.class || paramType == Integer.class) return n.intValue();
            if (paramType == long.class || paramType == Long.class) return n.longValue();
            if (paramType == double.class || paramType == Double.class) return n.doubleValue();
            if (paramType == float.class || paramType == Float.class) return n.floatValue();
            if (paramType == short.class || paramType == Short.class) return n.shortValue();
            if (paramType == byte.class || paramType == Byte.class) return n.byteValue();
        }
        return arg;
    }

    // ── Closures ──

    private static final ThreadLocal<Object[]> funcPool =
        ThreadLocal.withInitial(() -> new Object[0]);

    /** Register constant pool for closure creation via funcIdx. */
    public static void setFuncPool(Object[] pool) { funcPool.set(pool); }
    public static void clearFuncPool() { funcPool.remove(); }

    // ── Provided arg count for default parameter handling ──
    // Uses ThreadLocal to avoid cross-thread interference in concurrent execution.
    // Per JLS §17, each thread sees its own initial value (0).

    private static final ThreadLocal<int[]> providedArgCount =
        ThreadLocal.withInitial(() -> new int[1]);

    /** Set the actual number of arguments passed (before default filling). */
    public static void setProvidedArgCount(int n) { providedArgCount.get()[0] = n; }
    /** Get the actual number of arguments passed. */
    public static int getProvidedArgCount() { return providedArgCount.get()[0]; }
    /** Clear the provided arg count (call after bytecode execution). */
    public static void clearProvidedArgCount() { providedArgCount.remove(); }

    public static IRClosure createClosure(IRFunction fn, Object[] captured) {
        return new IRClosure(fn, captured);
    }

    /** Create closure by pool index (for bytecode — LDC can't embed IRFunction). */
    public static IRClosure createClosureById(int funcIdx, Object[] captured) {
        IRFunction fn = (IRFunction) funcPool.get()[funcIdx];
        // Capture evalContext so captured variables resolve in the
        // original enclosing scope. Try the ELContext first (bytecode
        // mode stores it there), then fall back to ThreadLocal.
        org.operamasks.el.eval.EvaluationContext evalCtx = null;
        try {
            javax.el.ELContext elctx = ELEngine.getCurrentELContext();
            if (elctx != null)
                evalCtx = (org.operamasks.el.eval.EvaluationContext)
                    elctx.getContext(org.operamasks.el.eval.EvaluationContext.class);
        } catch (Exception ignored) {}
        return new IRClosure(fn, captured, evalCtx);
    }

    // ── Locals / IncDec ──

    public static Object incLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l + 1;
        else if (val instanceof Integer i)
            val = i + 1;
        else if (val instanceof Double d)
            val = d + 1.0;
        else
            val = ((Number) val).longValue() + 1;
        locals[idx] = val;
        return val;
    }

    public static Object decLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l - 1;
        else if (val instanceof Integer i)
            val = i - 1;
        else if (val instanceof Double d)
            val = d - 1.0;
        else
            val = ((Number) val).longValue() - 1;
        locals[idx] = val;
        return val;
    }

    // ── Math ──

    public static Object intPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).intValue(), ((Number) y).intValue());
    }

    public static Object longPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).longValue(), ((Number) y).longValue());
    }

    public static Object doublePow(Object x, Object y) {
        return Math.pow(((Number) x).doubleValue(), ((Number) y).doubleValue());
    }

    // ── Bitwise ──

    public static Object bitAnd(Object a, Object b) {
        return ((Number) a).longValue() & ((Number) b).longValue();
    }

    public static Object bitOr(Object a, Object b) {
        return ((Number) a).longValue() | ((Number) b).longValue();
    }

    public static Object bitXor(Object a, Object b) {
        return ((Number) a).longValue() ^ ((Number) b).longValue();
    }

    public static Object bitShl(Object a, Object b) {
        return ((Number) a).longValue() << ((Number) b).longValue();
    }

    public static Object bitShr(Object a, Object b) {
        return ((Number) a).longValue() >> ((Number) b).longValue();
    }

    public static Object bitUshr(Object a, Object b) {
        return ((Number) a).longValue() >>> ((Number) b).longValue();
    }

    public static Object bitNot(Object a) {
        return ~((Number) a).longValue();
    }

    // ── Dynamic ops ──

    // ── Type-resolution framework matching ELNode.Arithmetic.evaluate() ──

    private interface ArithmeticOp {
        Number eval(BigDecimal x, BigDecimal y);
        Number eval(BigInteger x, BigInteger y);
        Number eval(Decimal x, Decimal y);
        Number eval(Rational x, Rational y);
        Number eval(double x, double y);
        Number eval(long x, long y);
        Number eval(int x, int y);
    }

    /** Overflow detection constants (matching ELNode.Arithmetic). */
    private static final long LONG_SIG_BIT = 1L << 63;
    private static final int  INT_SIG_BIT  = 1 << 31;

    private static final ArithmeticOp ADD_OP = new ArithmeticOp() {
        @Override
        public Number eval(BigDecimal x, BigDecimal y) {
            return x.add(y);
        }

        @Override
        public Number eval(BigInteger x, BigInteger y) {
            return x.add(y);
        }

        @Override
        public Number eval(Decimal x, Decimal y) {
            return x.add(y);
        }

        @Override
        public Number eval(Rational x, Rational y) {
            return x.add(y).reduce();
        }

        @Override
        public Number eval(double x, double y) {
            return x + y;
        }

        @Override
        public Number eval(long x, long y) {
            long z = x + y;
            if ((~(x ^ y) & (x ^ z) & LONG_SIG_BIT) != 0) {
                return BigInteger.valueOf(x).add(BigInteger.valueOf(y));
            } else {
                return z;
            }
        }

        @Override
        public Number eval(int x, int y) {
            int z = x + y;
            if ((~(x ^ y) & (x ^ z) & INT_SIG_BIT) != 0) {
                return (long)x + (long)y;
            } else {
                return z;
            }
        }
    };

    private static final ArithmeticOp SUB_OP = new ArithmeticOp() {
        @Override
        public Number eval(BigDecimal x, BigDecimal y) {
            return x.subtract(y);
        }

        @Override
        public Number eval(BigInteger x, BigInteger y) {
            return x.subtract(y);
        }

        @Override
        public Number eval(Decimal x, Decimal y) {
            return x.subtract(y);
        }

        @Override
        public Number eval(Rational x, Rational y) {
            return x.subtract(y).reduce();
        }

        @Override
        public Number eval(double x, double y) {
            return x - y;
        }

        @Override
        public Number eval(long x, long y) {
            long z = x - y;
            if ((~(x ^ ~y) & (x ^ z) & LONG_SIG_BIT) != 0) {
                return BigInteger.valueOf(x).subtract(BigInteger.valueOf(y));
            } else {
                return z;
            }
        }

        @Override
        public Number eval(int x, int y) {
            int z = x - y;
            if ((~(x ^ -y) & (x ^ z) & INT_SIG_BIT) != 0) {
                return (long)x - (long)y;
            } else {
                return z;
            }
        }
    };

    private static final ArithmeticOp MUL_OP = new ArithmeticOp() {
        @Override
        public Number eval(BigDecimal x, BigDecimal y) {
            return x.multiply(y);
        }

        @Override
        public Number eval(BigInteger x, BigInteger y) {
            return x.multiply(y);
        }

        @Override
        public Number eval(Decimal x, Decimal y) {
            return x.multiply(y);
        }

        @Override
        public Number eval(Rational x, Rational y) {
            return x.multiply(y).reduce();
        }

        @Override
        public Number eval(double x, double y) {
            return x * y;
        }

        @Override
        public Number eval(long x, long y) {
            long z = x * y;
            if (y != 0L && z/y != x) {       // overflowed
                return BigInteger.valueOf(x).multiply(BigInteger.valueOf(y));
            } else {
                return z;
            }
        }

        @Override
        public Number eval(int x, int y) {
            int z = x * y;
            if (y != 0 && z/y != x) {       // overflowed
                return (long)x * (long)y;
            } else {
                return z;
            }
        }
    };

    private static ArithmeticOp DIV_OP = new ArithmeticOp() {
        @Override
        public Number eval(BigDecimal x, BigDecimal y) {
            MathContext mc = new MathContext(
                    (int)Math.min(x.precision() +
                                  (long)Math.ceil(10.0*y.precision()/3.0),
                                  Integer.MAX_VALUE),
                    RoundingMode.HALF_UP);
            return x.divide(y, mc);
        }

        @Override
        public Number eval(BigInteger x, BigInteger y) {
            BigInteger[] r = x.divideAndRemainder(y);
            if (r[1].equals(BigInteger.ZERO)) {
                return r[0];
            } else {
                return eval(new BigDecimal(x), new BigDecimal(y));
            }
        }

        @Override
        public Number eval(Decimal x, Decimal y) {
            return x.divide(y);
        }

        @Override
        public Number eval(Rational x, Rational y) {
            return x.divide(y).reduce();
        }

        @Override
        public Number eval(double x, double y) {
            return x / y;
        }

        @Override
        public Number eval(long x, long y) {
            if (x % y == 0)
                return x / y;
            else
                return (double)x / (double)y;
        }

        @Override
        public Number eval(int x, int y) {
            if (x % y == 0)
                return x / y;
            else
                return (double)x / (double)y;
        }
    };

    private static final ArithmeticOp REM_OP = new ArithmeticOp() {
        @Override
        public Number eval(BigDecimal x, BigDecimal y) {
            return x.remainder(y);
        }

        @Override
        public Number eval(BigInteger x, BigInteger y) {
            return x.remainder(y);
        }

        @Override
        public Number eval(Decimal x, Decimal y) {
            return x.remainder(y);
        }

        @Override
        public Number eval(Rational x, Rational y) {
            return x.remainder(y).reduce();
        }

        @Override
        public Number eval(double x, double y) {
            return x % y;
        }

        @Override
        public Number eval(long x, long y) {
            return x % y;
        }

        @Override
        public Number eval(int x, int y) {
            return x % y;
        }
    };

    /** Shared type resolver for binary arithmetic. Matches AST's Arithmetic.evaluate(). */
    private static Object resolveBinOp(Object x, Object y, String op, ArithmeticOp arith) {
        if (x == null || y == null)
            throw new NullPointerException(_T(EL_NULL_OPERAND, op));

        if (x.getClass() == y.getClass()) {
            // Integer: use int op with overflow detection → promote to Long if needed
            if (x instanceof Long)
                return arith.eval((Long)x, (Long)y);
            if (x instanceof Integer)
                return arith.eval((Integer)x, (Integer)y);
            if (x instanceof Double)
                return arith.eval((Double)x, (Double)y);
            if (x instanceof Float)
                return arith.eval((Float)x, (Float)y);
            if (x instanceof Short)
                return arith.eval(((Short)x).intValue(), ((Short)y).intValue());
            if (x instanceof Byte)
                return arith.eval(((Byte)x).intValue(), ((Byte)y).intValue());
            if (x instanceof Decimal dx && y instanceof Decimal dy)
                return arith.eval(dx, dy);
            if (x instanceof Rational rx && y instanceof Rational ry)
                return arith.eval(rx, ry);
            if (x instanceof BigInteger bx && y instanceof BigInteger by)
                return arith.eval(bx, by);
            if (x instanceof BigDecimal bx && y instanceof BigDecimal by)
                return arith.eval(bx, by);
        }

        // Mixed types: promote to the wider type
        if (x instanceof BigDecimal || y instanceof BigDecimal)
            return arith.eval(TypeCoercion.coerceToBigDecimal(x),
                              TypeCoercion.coerceToBigDecimal(y));
        if (x instanceof Decimal || y instanceof Decimal)
            return arith.eval(TypeCoercion.coerceToDecimal(x),
                              TypeCoercion.coerceToDecimal(y));
        if (x instanceof Float || x instanceof Double ||
            y instanceof Float || y instanceof Double ||
            looksLikeFloat(x) || looksLikeFloat(y))
            return arith.eval(TypeCoercion.coerceToDouble(x),
                              TypeCoercion.coerceToDouble(y));
        if (x instanceof Rational || y instanceof Rational)
            return arith.eval(TypeCoercion.coerceToRational(x),
                              TypeCoercion.coerceToRational(y));
        if (x instanceof BigInteger || y instanceof BigInteger)
            return arith.eval(TypeCoercion.coerceToBigInteger(x),
                              TypeCoercion.coerceToBigInteger(y));
        if (x instanceof Long || y instanceof Long)
            return arith.eval(TypeCoercion.coerceToLong(x),
                              TypeCoercion.coerceToLong(y));

        // Fallback: promote to int (may lose precision for non-standard Number types)
        return arith.eval(TypeCoercion.coerceToInt(x),
                          TypeCoercion.coerceToInt(y));
    }

    private static boolean looksLikeFloat(Object v) {
        if (v instanceof CharSequence s) {
            int len = s.length();
            for (int i = 0; i < len; i++) {
                char c = s.charAt(i);
                if (c == '.' || c == 'e' || c == 'E')
                    return true;
            }
        }
        return false;
    }

    public static Object dynAdd(Object x, Object y) {
        return resolveBinOp(x, y, "+", ADD_OP);
    }

    public static Object dynSub(Object x, Object y) {
        return resolveBinOp(x, y, "-", SUB_OP);
    }

    public static Object dynMul(Object x, Object y) {
        return resolveBinOp(x, y, "*", MUL_OP);
    }

    public static Object dynDiv(Object x, Object y) {
        return resolveBinOp(x, y, "/", DIV_OP);
    }

    public static Object dynRem(Object x, Object y) {
        return resolveBinOp(x, y, "%", REM_OP);
    }

    public static Object dynNeg(Object x) {
        if (x == null)
            throw new NullPointerException();
        if (x instanceof Integer)
            return -((Integer)x);
        if (x instanceof Long)
            return -((Long)x);
        if (x instanceof Double)
            return -((Double)x);
        if (x instanceof Float)
            return -((Float)x).doubleValue();
        if (x instanceof Short)
            return -((Short)x);
        if (x instanceof Byte)
            return -((Byte)x);
        if (x instanceof BigDecimal bd)
            return bd.negate();
        if (x instanceof java.math.BigInteger bi)
            return bi.negate();
        if (x instanceof elite.lang.Rational r)
            return r.negate();
        if (x instanceof elite.lang.Decimal d)
            return d.negate();
        return -((Number)x).doubleValue();
    }

    public static Object dynPow(Object x, Object y) {
        if (x == null || y == null)
            throw new NullPointerException();
        if (x instanceof Number xn && y instanceof Number yn)
            return pow(xn, yn);
        return Math.pow(TypeCoercion.coerceToDouble(x), TypeCoercion.coerceToDouble(y));
    }

    private static Number pow(Number x, Number y) {
        if (y instanceof Long) {
            long n = y.longValue();
            if ((int)n == n)
                return pow(x, (int)n);
            else
                return Math.pow(x.doubleValue(), n);
        }
        if (y instanceof Integer || y instanceof Short || y instanceof Byte)
            return pow(x, y.intValue());
        return Math.pow(x.doubleValue(), y.doubleValue());
    }

    private static Number pow(Number x, int n) {
        if (x instanceof BigInteger bi) {
            if (n == 0)
                return 1;
            if (n == 1)
                return x;
            if (n > 0)
                return bi.pow(n);
            return Math.pow(bi.doubleValue(), n);
        }

        if (x instanceof Long || x instanceof Integer || x instanceof Short || x instanceof Byte) {
            long m = x.longValue();
            if (n == 0)
                return 1;
            if (n == 1)
                return m;
            if (n > 0) {
                BigInteger z = BigInteger.valueOf(m).pow(n);
                return z.bitLength() < 32 ? z.intValue()
                     : z.bitLength() < 64 ? z.longValue() : z;
            }
            return Math.pow(x.doubleValue(), n);
        }

        if (x instanceof BigDecimal bd) {
            return bd.pow(n);
        }
        if (x instanceof Decimal d) {
            return Decimal.valueOf(d.toBigDecimal().pow(n));
        }
        if (x instanceof Rational r) {
            return r.pow(n).reduce();
        }
        return Math.pow(x.doubleValue(), n);
    }

    public static Object dynCat(ELContext c, Object x, Object y) {
        // Java-compatible null handling: null → "null" for string operations
        if (x == null) x = "null";
        if (y == null) y = "null";

        if (x instanceof Closure cx && y instanceof Closure cy) {
            return cx.compose(cy);
        }

        if (x instanceof Seq sx) {
            return y instanceof Collection<?>
                ? sx.append(TypeCoercion.coerceToSeq(y))
                : sx.append(Cons.make(y));
        }
        if (x instanceof Collection<?> cx) {
            ArrayList<Object> result = new ArrayList<>(cx);
            if (y instanceof Collection<?> cy)
                result.addAll(cy);
            else
                result.add(y);
            return result;
        }
        if (x.getClass().isArray()) {
            Class<?> ct = x.getClass().getComponentType();
            int xlen = Array.getLength(x);
            if (y.getClass() == x.getClass()) {
                // concatenate arraies with same type
                int ylen = Array.getLength(y);
                Object a = Array.newInstance(ct, xlen + ylen);
                System.arraycopy(x, 0, a, 0, xlen);
                System.arraycopy(y, 0, a, xlen, ylen);
                return a;
            } else if (y.getClass().isArray()) {
                // concatenate arraies with different type
                int ylen = Array.getLength(y);
                Object[] a = new Object[xlen + ylen];
                for (int i = 0; i < xlen; i++) a[i] = Array.get(x, i);
                for (int i = 0; i < ylen; i++) a[xlen + i] = Array.get(y, i);
                return a;
            } else {
                // concatenate an array with an element
                Object a = Array.newInstance(ct, xlen + 1);
                System.arraycopy(x, 0, a, 0, xlen);
                Array.set(a, xlen, tryCoerce(c, y, ct));
                return a;
            }
        }
        if (y instanceof Seq sy) {
            return new Cons(x, sy);
        }
        if (y instanceof Collection<?> cy) {
            ArrayList<Object> result = new ArrayList<>();
            result.add(x);
            result.addAll(cy);
            return result;
        }
        if (y.getClass().isArray()) {
            Class<?> ct = y.getClass().getComponentType();
            int len = Array.getLength(y);
            Object a = Array.newInstance(ct, len + 1);
            Array.set(a, 0, tryCoerce(c, x, ct));
            System.arraycopy(y, 0, a, 1, len);
            return a;
        }
        return String.valueOf(x) + y;
    }

    private static Object tryCoerce(ELContext c, Object v, Class<?> t) {
        try { return c != null ? org.operamasks.el.eval.TypeCoercion.coerce(c, v, t) : v; }
        catch (Exception e) { return v; }
    }

    /** Equality comparison following ELNode.Equality.evaluate() type resolution. */
    public static Object dynEq(Object x, Object y) {
        return equality(x, y, true);
    }
    public static Object dynNe(Object x, Object y) {
        return equality(x, y, false);
    }
    private static boolean equality(Object x, Object y, boolean isEq) {
        if (x == y) return isEq;
        if (x == null || y == null) return !isEq;

        Class<?> xc = x.getClass(), yc = y.getClass();
        if (xc == yc) {
            if (x instanceof Number) return isEq == numEq((Number)x, (Number)y);
            if (x instanceof Object[]) return isEq == arrayEq((Object[])x, (Object[])y);
            return isEq == x.equals(y);
        }

        if (x instanceof Number && y instanceof Number) {
            if (x instanceof org.operamasks.el.eval.closure.ClosureObject) return isEq == x.equals(y);
            if (x instanceof java.math.BigDecimal || y instanceof java.math.BigDecimal)
                return isEq == numEq(org.operamasks.el.eval.TypeCoercion.coerceToBigDecimal(x),
                                    org.operamasks.el.eval.TypeCoercion.coerceToBigDecimal(y));
            if (x instanceof elite.lang.Decimal || y instanceof elite.lang.Decimal)
                return isEq == numEq(org.operamasks.el.eval.TypeCoercion.coerceToDecimal(x),
                                    org.operamasks.el.eval.TypeCoercion.coerceToDecimal(y));
            if (x instanceof Float || y instanceof Float || x instanceof Double || y instanceof Double)
                return isEq == (org.operamasks.el.eval.TypeCoercion.coerceToDouble(x)
                             == org.operamasks.el.eval.TypeCoercion.coerceToDouble(y));
            if (x instanceof elite.lang.Rational || y instanceof elite.lang.Rational)
                return isEq == numEq(org.operamasks.el.eval.TypeCoercion.coerceToRational(x),
                                    org.operamasks.el.eval.TypeCoercion.coerceToRational(y));
            if (x instanceof java.math.BigInteger || y instanceof java.math.BigInteger)
                return isEq == numEq(org.operamasks.el.eval.TypeCoercion.coerceToBigInteger(x),
                                    org.operamasks.el.eval.TypeCoercion.coerceToBigInteger(y));
            return isEq == (org.operamasks.el.eval.TypeCoercion.coerceToLong(x)
                         == org.operamasks.el.eval.TypeCoercion.coerceToLong(y));
        }

        if (x instanceof Boolean || y instanceof Boolean)
            return isEq == (org.operamasks.el.eval.TypeCoercion.coerceToBoolean(x)
                         == org.operamasks.el.eval.TypeCoercion.coerceToBoolean(y));
        if (x instanceof Enum || y instanceof Enum) {
            if (!(x instanceof Enum)) x = org.operamasks.el.eval.TypeCoercion.coerceToEnum(x, ((Enum<?>)y).getClass());
            if (!(y instanceof Enum)) y = org.operamasks.el.eval.TypeCoercion.coerceToEnum(y, ((Enum<?>)x).getClass());
            return isEq == x.equals(y);
        }
        if (x instanceof String || y instanceof String)
            return isEq == x.toString().equals(y.toString());
        if (x instanceof Object[] && y instanceof Object[])
            return isEq == arrayEq((Object[])x, (Object[])y);
        if (x instanceof Character && y instanceof Number
            || x instanceof Number && y instanceof Character)
            return isEq == (org.operamasks.el.eval.TypeCoercion.coerceToCharacter(x)
                         == org.operamasks.el.eval.TypeCoercion.coerceToCharacter(y));
        return isEq == x.equals(y);
    }
    private static boolean numEq(Number x, Number y) {
        return x.doubleValue() == y.doubleValue();
    }
    private static boolean arrayEq(Object[] x, Object[] y) {
        if (x.length != y.length) return false;
        for (int i = 0; i < x.length; i++) {
            if (!equality(x[i], y[i], true)) return false;
        }
        return true;
    }

    /** Comparison following ELNode.Comparison.evaluate() type resolution. */
    public static Object dynLt(Object x, Object y) { return compare(x, y, Token.LT); }
    public static Object dynLe(Object x, Object y) { return compare(x, y, Token.LE); }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private static boolean compare(Object x, Object y, int op) {
        if (x == y) return op == Token.LE || op == Token.GE;
        if (x == null || y == null) return false;

        Class<?> xc = x.getClass(), yc = y.getClass();
        if (xc == yc) {
            if (x instanceof Comparable) return cmp((Comparable)x, (Comparable)y, op);
        }

        if (x instanceof java.math.BigDecimal || y instanceof java.math.BigDecimal)
            return cmp(org.operamasks.el.eval.TypeCoercion.coerceToBigDecimal(x),
                       org.operamasks.el.eval.TypeCoercion.coerceToBigDecimal(y), op);
        if (x instanceof elite.lang.Decimal || y instanceof elite.lang.Decimal)
            return cmp(org.operamasks.el.eval.TypeCoercion.coerceToDecimal(x),
                       org.operamasks.el.eval.TypeCoercion.coerceToDecimal(y), op);
        if (x instanceof Float || y instanceof Float || x instanceof Double || y instanceof Double)
            return cmp((Comparable)org.operamasks.el.eval.TypeCoercion.coerceToDouble(x),
                       (Comparable)org.operamasks.el.eval.TypeCoercion.coerceToDouble(y), op);
        if (x instanceof elite.lang.Rational || y instanceof elite.lang.Rational)
            return cmp(org.operamasks.el.eval.TypeCoercion.coerceToRational(x),
                       org.operamasks.el.eval.TypeCoercion.coerceToRational(y), op);
        if (x instanceof java.math.BigInteger || y instanceof java.math.BigInteger)
            return cmp(org.operamasks.el.eval.TypeCoercion.coerceToBigInteger(x),
                       org.operamasks.el.eval.TypeCoercion.coerceToBigInteger(y), op);
        if (x instanceof Number || y instanceof Number)
            return cmp((Comparable)org.operamasks.el.eval.TypeCoercion.coerceToLong(x),
                       (Comparable)org.operamasks.el.eval.TypeCoercion.coerceToLong(y), op);
        if (x instanceof String || y instanceof String)
            return cmp(x.toString(), y.toString(), op);
        if (x instanceof Comparable && y instanceof Comparable)
            return cmp((Comparable)x, (Comparable)y, op);
        throw new RuntimeException(_T(EL_CANNOT_COMPARE, xc.getName(), yc.getName()));
    }
    @SuppressWarnings({"unchecked", "rawtypes"})
    private static boolean cmp(Comparable a, Comparable b, int op) {
        int c = a.compareTo(b);
        return switch (op) {
            case Token.LT -> c < 0;
            case Token.LE -> c <= 0;
            case Token.GT -> c > 0;
            case Token.GE -> c >= 0;
            default -> false;
        };
    }

    // ── Type guard ──

    public static void guardTypeStrict(Object val, int typeId) {
        if (!checkGuardType(val, typeId)) {
            String expected = IRFormat.primTypeName(typeId);
            String actual = val == null ? "null" : val.getClass().getName();
            throw new RuntimeException(_T(IR_TYPE_MISMATCH, expected, actual));
        }
    }

    private static boolean checkGuardType(Object val, int typeId) {
        if (val == null)
            return false;
        return switch (typeId) {
            case IRFormat.T_INT ->
                    val instanceof Integer || val instanceof Short || val instanceof Byte || val instanceof Long;
            case IRFormat.T_LONG ->
                    val instanceof Long || val instanceof Integer || val instanceof Short || val instanceof Byte;
            case IRFormat.T_DOUBLE ->
                    val instanceof Double || val instanceof Float || val instanceof Long || val instanceof Integer;
            case IRFormat.T_BOOL -> val instanceof Boolean;
            case IRFormat.T_STRING -> val instanceof String;
            default -> true;
        };
    }
}
