/*
 * Copyright 2006-2026 Daniel Yuan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package elite.rt;

import javax.el.ELContext;

import elite.lang.Closure;
import elite.lang.Seq;
import org.operamasks.el.eval.ELEngine;
import org.operamasks.el.ir.IRClosure;
import org.operamasks.el.ir.IRFormat;
import org.operamasks.el.ir.IRFunction;
import org.operamasks.el.ir.IRInterpreter;

/**
 * Runtime support methods called from ELite-generated bytecode via {@code invokestatic}.
 */
public final class Runtime {

    private Runtime() {
    }

    // ── ELContext-dependent helpers ──

    public static Object pushGlobal(ELContext c, String name) {
        javax.el.ValueExpression ve = c.getVariableMapper().resolveVariable(name);
        if (ve != null)
            return ve.getValue(c);
        // Check FunctionMapper for global/imported functions
        org.operamasks.el.resolver.MethodResolver mr =
            org.operamasks.el.resolver.MethodResolver.getInstance(c);
        if (mr != null) {
            org.operamasks.el.eval.closure.MethodClosure mc =
                mr.resolveGlobalMethod(c.getFunctionMapper(), name);
            if (mc != null)
                return mc;
        }
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, null, name);
        if (c.isPropertyResolved())
            return r;
        throw new RuntimeException("Undefined: " + name);
    }

    public static Object storeGlobal(ELContext c, String name, Object value) {
        c.getVariableMapper().setVariable(name, new org.operamasks.el.eval.closure.LiteralClosure(value));
        return value;
    }

    public static Object loadProp(ELContext c, Object base, Object key) {
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, base, key);
        if (!c.isPropertyResolved())
            throw new RuntimeException("Property not found: " + key);
        return r;
    }

    public static Object storeProp(ELContext c, Object base, Object key, Object value) {
        c.getELResolver().setValue(c, base, key, value);
        return value;
    }

    public static Object trampoline(ELContext c, Object nodeObj) {
        org.operamasks.el.parser.ELNode node = (org.operamasks.el.parser.ELNode) nodeObj;
        return node.getValue(new org.operamasks.el.eval.EvaluationContext(c));
    }

    /** Evaluate a trampoline node by pool index (for bytecode — LDC can't embed ELNode). */
    public static Object trampolineById(ELContext c, int poolIdx) {
        return trampoline(c, funcPool.get()[poolIdx]);
    }

    /** Evaluate a TRY node via AST (using TryDescriptor's original TRY node). */
    public static Object trampolineTry(ELContext c, int poolIdx) {
        Object obj = funcPool.get()[poolIdx];
        if (obj instanceof org.operamasks.el.ir.TryDescriptor td) {
            return trampoline(c, td.tryNode);
        }
        return trampoline(c, obj);
    }

    /** Wrap a throwable value as RuntimeException for ATHROW bytecode. */
    public static RuntimeException wrapThrow(Object cause) {
        if (cause instanceof RuntimeException re) return re;
        if (cause instanceof Throwable t)
            return new org.operamasks.el.eval.UserException(null, t);
        if (cause instanceof String s)
            return new org.operamasks.el.eval.UserException(null, s);
        return new org.operamasks.el.eval.UserException(null);
    }

    public static Object invokeDyn(ELContext c, Object target, Object[] args) {
        if (target instanceof IRFunction irFn) {
            return new IRInterpreter(c, irFn, null).execute(args);
        }
        if (target instanceof IRClosure closure) {
            IRFunction irFn = closure.getFunction();
            int paramCount = irFn.paramCount();
            int captureCount = irFn.captureCount();
            Object[] expandedArgs = new Object[paramCount + captureCount];
            System.arraycopy(args, 0, expandedArgs, 0, Math.min(args.length, paramCount));
            System.arraycopy(closure.getCaptured(), 0, expandedArgs, paramCount, captureCount);
            return new IRInterpreter(c, irFn, null).execute(expandedArgs);
        }
        Closure[] closures = ELEngine.getCallArgs(args);
        return ELEngine.invokeTarget(c, target, closures);
    }

    // ── Collections ──

    public static Object newList(Object[] elems) {
        return java.util.Arrays.asList(elems);
    }

    public static Object newMap(Object[] kvs) {
        java.util.LinkedHashMap<Object, Object> m = new java.util.LinkedHashMap<>();
        for (int i = 0; i < kvs.length; i += 2)
            m.put(kvs[i], kvs[i + 1]);
        return m;
    }

    public static Object newTuple(Object[] elems) {
        return elems;
    }

    public static Object newRange(Object begin, Object end) {
        return org.operamasks.el.eval.Ranges.createRange(
                ((Number)begin).longValue(), ((Number)end).longValue(), 1);
    }

    public static Object contains(Object coll, Object elem) {
        if (coll instanceof java.util.Collection<?> c)
            return c.contains(elem);
        if (coll instanceof Object[] a) {
            for (Object o : a)
                if (java.util.Objects.equals(o, elem))
                    return true;
            return false;
        }
        if (coll instanceof Seq seq) {
            while (!seq.isEmpty()) {
                if (java.util.Objects.equals(seq.head(), elem))
                    return true;
                seq = seq.tail();
            }
        }
        return false;
    }

    public static Object getIter(Object coll) {
        return IRInterpreter.getIterator(coll);
    }

    public static Object iterNext(Object it) {
        java.util.Iterator<?> iter = (java.util.Iterator<?>) it;
        return iter.hasNext() ? iter.next() : null;
    }

    // ── Field access ──

    public static Object loadField(Object base, String name) {
        if (base == null)
            throw new NullPointerException("Cannot read field '" + name + "' from null");
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            return f.get(target);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException("Field not found: " + name + " on " + base.getClass().getName());
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Cannot access field: " + name, e);
        }
    }

    public static Object storeFieldBC(Object value, Object base, String name) {
        if (base == null)
            throw new NullPointerException("Cannot write field '" + name + "' to null");
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            f.set(target, coerceArg(value, f.getType()));
            return value;
        } catch (NoSuchFieldException e) {
            throw new RuntimeException("Field not found: " + name + " on " + base.getClass().getName());
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Cannot access field: " + name, e);
        }
    }

    private static Object coerceArg(Object arg, Class<?> paramType) {
        if (arg == null || paramType.isInstance(arg)) return arg;
        if (arg instanceof Number n) {
            if (paramType == int.class || paramType == Integer.class) return n.intValue();
            if (paramType == long.class || paramType == Long.class) return n.longValue();
            if (paramType == double.class || paramType == Double.class) return n.doubleValue();
            if (paramType == float.class || paramType == Float.class) return n.floatValue();
            if (paramType == short.class || paramType == Short.class) return n.shortValue();
            if (paramType == byte.class || paramType == Byte.class) return n.byteValue();
        }
        return arg;
    }

    // ── Closures ──

    private static final ThreadLocal<Object[]> funcPool =
        ThreadLocal.withInitial(() -> new Object[0]);

    /** Register constant pool for closure creation via funcIdx. */
    public static void setFuncPool(Object[] pool) { funcPool.set(pool); }
    public static void clearFuncPool() { funcPool.remove(); }

    public static IRClosure createClosure(IRFunction fn, Object[] captured) {
        return new IRClosure(fn, captured);
    }

    /** Create closure by pool index (for bytecode — LDC can't embed IRFunction). */
    public static IRClosure createClosureById(int funcIdx, Object[] captured) {
        return new IRClosure((IRFunction) funcPool.get()[funcIdx], captured);
    }

    // ── Locals / IncDec ──

    public static Object incLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l + 1;
        else if (val instanceof Integer i)
            val = i + 1;
        else if (val instanceof Double d)
            val = d + 1.0;
        else
            val = ((Number) val).longValue() + 1;
        locals[idx] = val;
        return val;
    }

    public static Object decLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l - 1;
        else if (val instanceof Integer i)
            val = i - 1;
        else if (val instanceof Double d)
            val = d - 1.0;
        else
            val = ((Number) val).longValue() - 1;
        locals[idx] = val;
        return val;
    }

    // ── Math ──

    public static Object intPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).intValue(), ((Number) y).intValue());
    }

    public static Object longPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).longValue(), ((Number) y).longValue());
    }

    public static Object doublePow(Object x, Object y) {
        return Math.pow(((Number) x).doubleValue(), ((Number) y).doubleValue());
    }

    // ── Bitwise ──

    public static Object bitAnd(Object a, Object b) {
        return ((Number) a).longValue() & ((Number) b).longValue();
    }

    public static Object bitOr(Object a, Object b) {
        return ((Number) a).longValue() | ((Number) b).longValue();
    }

    public static Object bitXor(Object a, Object b) {
        return ((Number) a).longValue() ^ ((Number) b).longValue();
    }

    public static Object bitShl(Object a, Object b) {
        return ((Number) a).longValue() << ((Number) b).longValue();
    }

    public static Object bitShr(Object a, Object b) {
        return ((Number) a).longValue() >> ((Number) b).longValue();
    }

    public static Object bitUshr(Object a, Object b) {
        return ((Number) a).longValue() >>> ((Number) b).longValue();
    }

    public static Object bitNot(Object a) {
        return ~((Number) a).longValue();
    }

    // ── Dynamic ops ──

    // ── Type-resolution framework matching ELNode.Arithmetic.evaluate() ──

    @FunctionalInterface
    private interface NumOp { Object eval(long x, long y); }

    /** Shared type resolver for binary arithmetic. Matches AST's Arithmetic.evaluate(). */
    private static Object resolveBinOp(Object x, Object y, String op,
                                        NumOp longOp, java.util.function.DoubleBinaryOperator doubleOp,
                                        NumOp bigIntOp, NumOp bigDecOp, NumOp rationalOp, NumOp decimalOp) {
        if (x == null || y == null) throw new NullPointerException("Null operand in " + op);
        Class<?> xc = x.getClass(), yc = y.getClass();
        if (xc == yc) {
            if (x instanceof Long)       return longOp.eval((Long)x, (Long)y);
            if (x instanceof Integer)    return longOp.eval((Integer)x, (Integer)y);
            if (x instanceof Double)     return doubleOp.applyAsDouble((Double)x, (Double)y);
            if (x instanceof Float)      return doubleOp.applyAsDouble((Float)x, (Float)y);
            if (x instanceof Short)      return longOp.eval((Short)x, (Short)y);
            if (x instanceof Byte)       return longOp.eval((Byte)x, (Byte)y);
            if (x instanceof elite.lang.Decimal dx && y instanceof elite.lang.Decimal dy) return decimalOp.eval(0,0);
            if (x instanceof elite.lang.Rational rx && y instanceof elite.lang.Rational ry) return rationalOp.eval(0,0);
            if (x instanceof java.math.BigInteger bx && y instanceof java.math.BigInteger by) return bigIntOp.eval(0,0);
            if (x instanceof java.math.BigDecimal bx && y instanceof java.math.BigDecimal by) return bigDecOp.eval(0,0);
        }
        if (x instanceof java.math.BigDecimal || y instanceof java.math.BigDecimal)
            return bigDecOp.eval(0,0);
        if (x instanceof elite.lang.Decimal || y instanceof elite.lang.Decimal)
            return decimalOp.eval(0,0);
        if (x instanceof Float || x instanceof Double || y instanceof Float || y instanceof Double
            || looksLikeFloat(x) || looksLikeFloat(y))
            return doubleOp.applyAsDouble(((Number)x).doubleValue(), ((Number)y).doubleValue());
        if (x instanceof elite.lang.Rational || y instanceof elite.lang.Rational)
            return rationalOp.eval(0,0);
        if (x instanceof java.math.BigInteger || y instanceof java.math.BigInteger)
            return bigIntOp.eval(0,0);
        if (x instanceof Long || y instanceof Long)
            return longOp.eval(((Number)x).longValue(), ((Number)y).longValue());
        return longOp.eval(((Number)x).intValue(), ((Number)y).intValue());
    }
    private static boolean looksLikeFloat(Object v) {
        if (!(v instanceof Number n)) return false;
        if (n instanceof Float || n instanceof Double) return true;
        String s = n.toString();
        return s.indexOf('.') >= 0 || s.indexOf('e') >= 0 || s.indexOf('E') >= 0;
    }

    public static Object dynAdd(Object x, Object y) {
        return resolveBinOp(x, y, "+",
            (a,b)->a+b, (a,b)->a+b,
            (a,b)->((java.math.BigInteger)x).add((java.math.BigInteger)y),
            (a,b)->((java.math.BigDecimal)x).add((java.math.BigDecimal)y),
            (a,b)->((elite.lang.Rational)x).add((elite.lang.Rational)y).reduce(),
            (a,b)->((elite.lang.Decimal)x).add((elite.lang.Decimal)y));
    }
    public static Object dynSub(Object x, Object y) {
        return resolveBinOp(x, y, "-",
            (a,b)->a-b, (a,b)->a-b,
            (a,b)->((java.math.BigInteger)x).subtract((java.math.BigInteger)y),
            (a,b)->((java.math.BigDecimal)x).subtract((java.math.BigDecimal)y),
            (a,b)->((elite.lang.Rational)x).subtract((elite.lang.Rational)y).reduce(),
            (a,b)->((elite.lang.Decimal)x).subtract((elite.lang.Decimal)y));
    }
    public static Object dynMul(Object x, Object y) {
        return resolveBinOp(x, y, "*",
            (a,b)->a*b, (a,b)->a*b,
            (a,b)->((java.math.BigInteger)x).multiply((java.math.BigInteger)y),
            (a,b)->((java.math.BigDecimal)x).multiply((java.math.BigDecimal)y),
            (a,b)->((elite.lang.Rational)x).multiply((elite.lang.Rational)y).reduce(),
            (a,b)->((elite.lang.Decimal)x).multiply((elite.lang.Decimal)y));
    }
    public static Object dynDiv(Object x, Object y) {
        if (x instanceof Integer xi && y instanceof Integer yi) {
            if (yi==0) throw new ArithmeticException("/ by zero");
            return (xi % yi == 0) ? xi / yi : (double)xi / (double)yi;
        }
        if (x instanceof Long xl && y instanceof Long yl) {
            if (yl==0) throw new ArithmeticException("/ by zero");
            return (xl % yl == 0) ? xl / yl : (double)xl / (double)yl;
        }
        return resolveBinOp(x, y, "/",
            (a,b)->{throw new UnsupportedOperationException();},
            (a,b)->a/b,
            (a,b)->((java.math.BigInteger)x).divide((java.math.BigInteger)y),
            (a,b)->((java.math.BigDecimal)x).divide((java.math.BigDecimal)y, java.math.MathContext.DECIMAL128),
            (a,b)->((elite.lang.Rational)x).divide((elite.lang.Rational)y).reduce(),
            (a,b)->((elite.lang.Decimal)x).divide((elite.lang.Decimal)y));
    }
    public static Object dynRem(Object x, Object y) {
        return resolveBinOp(x, y, "%",
            (a,b)->a%b, (a,b)->a%b,
            (a,b)->((java.math.BigInteger)x).remainder((java.math.BigInteger)y),
            (a,b)->((java.math.BigDecimal)x).remainder((java.math.BigDecimal)y),
            (a,b)->null, // Rational doesn't support rem
            (a,b)->((elite.lang.Decimal)x).remainder((elite.lang.Decimal)y));
    }
    public static Object dynNeg(Object x) {
        if (x instanceof Integer) return -((Integer)x);
        if (x instanceof Long) return -((Long)x);
        if (x instanceof Double) return -((Double)x);
        if (x instanceof Float) return -((Float)x).doubleValue();
        if (x instanceof java.math.BigDecimal bd) return bd.negate();
        if (x instanceof java.math.BigInteger bi) return bi.negate();
        if (x instanceof elite.lang.Rational r) return r.negate();
        if (x instanceof elite.lang.Decimal d) return d.negate();
        return -((Number)x).doubleValue();
    }
    public static Object dynPow(Object x, Object y) {
        if (x == null || y == null) return null;
        if (!(x instanceof Number) || !(y instanceof Number))
            return Math.pow(((Number)x).doubleValue(), ((Number)y).doubleValue());
        return pow((Number)x, (Number)y);
    }
    private static Number pow(Number x, Number y) {
        if (y instanceof Long) {
            long n = y.longValue();
            if ((int)n == n) return pow(x, (int)n);
            else return Math.pow(x.doubleValue(), n);
        }
        if (y instanceof Integer || y instanceof Short || y instanceof Byte)
            return pow(x, y.intValue());
        return Math.pow(x.doubleValue(), y.doubleValue());
    }
    private static Number pow(Number x, int n) {
        if (x instanceof java.math.BigInteger bi) {
            if (n == 0) return 1;
            if (n == 1) return bi;
            if (n > 0) return bi.pow(n);
            return Math.pow(bi.doubleValue(), n);
        }
        if (x instanceof Long || x instanceof Integer || x instanceof Short || x instanceof Byte) {
            long m = x.longValue();
            if (n == 0) return 1;
            if (n == 1) return m;
            if (n > 0) {
                java.math.BigInteger z = java.math.BigInteger.valueOf(m).pow(n);
                return z.bitLength() < 32 ? z.intValue()
                     : z.bitLength() < 64 ? z.longValue() : z;
            }
            return Math.pow(x.doubleValue(), n);
        }
        if (x instanceof java.math.BigDecimal bd) {
            return bd.pow(n);
        }
        if (x instanceof elite.lang.Decimal d) {
            return elite.lang.Decimal.valueOf(d.toBigDecimal().pow(n));
        }
        if (x instanceof elite.lang.Rational r) {
            return r.pow(n).reduce();
        }
        return Math.pow(x.doubleValue(), n);
    }

    public static Object dynCat(Object x, Object y) {
        if (x == null) x = "null";
        if (y == null) y = "null";

        if (x instanceof Closure && y instanceof Closure) {
            return ((Closure)x).compose((Closure)y);
        }
        if (x instanceof Seq sx) {
            return y instanceof java.util.Collection<?> cy
                ? sx.append(coerceToSeq(cy)) : sx.append(org.operamasks.el.eval.seq.Cons.make(y));
        }
        if (x instanceof java.util.Collection<?> cx) {
            java.util.ArrayList<Object> result = new java.util.ArrayList<>(cx);
            if (y instanceof java.util.Collection<?> cy) result.addAll(cy);
            else result.add(y);
            return result;
        }
        if (x.getClass().isArray()) {
            Class<?> ct = x.getClass().getComponentType();
            int xlen = java.lang.reflect.Array.getLength(x);
            if (y.getClass() == x.getClass()) {
                int ylen = java.lang.reflect.Array.getLength(y);
                Object a = java.lang.reflect.Array.newInstance(ct, xlen + ylen);
                System.arraycopy(x, 0, a, 0, xlen);
                System.arraycopy(y, 0, a, xlen, ylen);
                return a;
            } else if (y.getClass().isArray()) {
                int ylen = java.lang.reflect.Array.getLength(y);
                Object[] a = new Object[xlen + ylen];
                for (int i = 0; i < xlen; i++) a[i] = java.lang.reflect.Array.get(x, i);
                for (int i = 0; i < ylen; i++) a[xlen + i] = java.lang.reflect.Array.get(y, i);
                return a;
            } else {
                Object a = java.lang.reflect.Array.newInstance(ct, xlen + 1);
                System.arraycopy(x, 0, a, 0, xlen);
                java.lang.reflect.Array.set(a, xlen, y);
                return a;
            }
        }
        if (y instanceof Seq sy) {
            return new org.operamasks.el.eval.seq.Cons(x, sy);
        }
        if (y instanceof java.util.Collection<?> cy) {
            java.util.ArrayList<Object> result = new java.util.ArrayList<>();
            result.add(x);
            result.addAll(cy);
            return result;
        }
        if (y.getClass().isArray()) {
            Class<?> ct = y.getClass().getComponentType();
            int len = java.lang.reflect.Array.getLength(y);
            Object a = java.lang.reflect.Array.newInstance(ct, len + 1);
            java.lang.reflect.Array.set(a, 0, x);
            System.arraycopy(y, 0, a, 1, len);
            return a;
        }
        return new StringBuilder().append(x).append(y).toString();
    }
    private static Seq coerceToSeq(java.util.Collection<?> c) {
        if (c instanceof Seq s) return s;
        return org.operamasks.el.eval.seq.Cons.make(c.toArray());
    }

    public static Object dynEq(Object x, Object y) {
        if (x == y) return true;
        if (x == null || y == null) return false;
        if (x instanceof Number && y instanceof Number) {
            return ((Number)x).doubleValue() == ((Number)y).doubleValue();
        }
        return java.util.Objects.equals(x, y);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Object dynLt(Object x, Object y) {
        if (x instanceof Comparable a && y instanceof Comparable b)
            return a.compareTo(b) < 0;
        return String.valueOf(x).compareTo(String.valueOf(y)) < 0;
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Object dynLe(Object x, Object y) {
        if (x instanceof Comparable a && y instanceof Comparable b)
            return a.compareTo(b) <= 0;
        return String.valueOf(x).compareTo(String.valueOf(y)) <= 0;
    }

    public static Object dynIn(Object x, Object y) {
        if (y instanceof java.util.Collection<?> c)
            return c.contains(x);
        return false;
    }

    // ── Type guard ──

    public static void guardTypeStrict(Object val, int typeId) {
        if (!checkGuardType(val, typeId)) {
            String expected = IRFormat.primTypeName(typeId);
            String actual = val == null ? "null" : val.getClass().getName();
            throw new RuntimeException("Type mismatch: expected " + expected + ", got " + actual);
        }
    }

    private static boolean checkGuardType(Object val, int typeId) {
        if (val == null)
            return false;
        return switch (typeId) {
            case IRFormat.T_INT ->
                    val instanceof Integer || val instanceof Short || val instanceof Byte || val instanceof Long;
            case IRFormat.T_LONG ->
                    val instanceof Long || val instanceof Integer || val instanceof Short || val instanceof Byte;
            case IRFormat.T_DOUBLE ->
                    val instanceof Double || val instanceof Float || val instanceof Long || val instanceof Integer;
            case IRFormat.T_BOOL -> val instanceof Boolean;
            case IRFormat.T_STRING -> val instanceof String;
            default -> true;
        };
    }
}
