/*
 * Copyright 2006-2026 Daniel Yuan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package elite.rt;

import javax.el.ELContext;

import elite.lang.Closure;
import elite.lang.Seq;
import org.operamasks.el.eval.ELEngine;
import org.operamasks.el.ir.IRClosure;
import org.operamasks.el.ir.IRFormat;
import org.operamasks.el.ir.IRFunction;
import org.operamasks.el.ir.IRInterpreter;

/**
 * Runtime support methods called from ELite-generated bytecode via {@code invokestatic}.
 */
public final class Runtime {

    private Runtime() {
    }

    // ── ELContext-dependent helpers ──

    public static Object pushGlobal(ELContext c, String name) {
        javax.el.ValueExpression ve = c.getVariableMapper().resolveVariable(name);
        if (ve != null)
            return ve.getValue(c);
        // Check FunctionMapper for global/imported functions
        org.operamasks.el.resolver.MethodResolver mr =
            org.operamasks.el.resolver.MethodResolver.getInstance(c);
        if (mr != null) {
            org.operamasks.el.eval.closure.MethodClosure mc =
                mr.resolveGlobalMethod(c.getFunctionMapper(), name);
            if (mc != null)
                return mc;
        }
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, null, name);
        if (c.isPropertyResolved())
            return r;
        throw new RuntimeException("Undefined: " + name);
    }

    public static Object storeGlobal(ELContext c, String name, Object value) {
        c.getVariableMapper().setVariable(name, new org.operamasks.el.eval.closure.LiteralClosure(value));
        return value;
    }

    public static Object loadProp(ELContext c, Object base, Object key) {
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, base, key);
        if (!c.isPropertyResolved())
            throw new RuntimeException("Property not found: " + key);
        return r;
    }

    public static Object storeProp(ELContext c, Object base, Object key, Object value) {
        c.getELResolver().setValue(c, base, key, value);
        return value;
    }

    public static Object trampoline(ELContext c, Object nodeObj) {
        org.operamasks.el.parser.ELNode node = (org.operamasks.el.parser.ELNode) nodeObj;
        return node.getValue(new org.operamasks.el.eval.EvaluationContext(c));
    }

    public static Object invokeDyn(ELContext c, Object target, Object[] args) {
        if (target instanceof IRFunction irFn) {
            return new IRInterpreter(c, irFn, null).execute(args);
        }
        if (target instanceof IRClosure closure) {
            IRFunction irFn = closure.getFunction();
            int paramCount = irFn.paramCount();
            int captureCount = irFn.captureCount();
            Object[] expandedArgs = new Object[paramCount + captureCount];
            System.arraycopy(args, 0, expandedArgs, 0, Math.min(args.length, paramCount));
            System.arraycopy(closure.getCaptured(), 0, expandedArgs, paramCount, captureCount);
            return new IRInterpreter(c, irFn, null).execute(expandedArgs);
        }
        Closure[] closures = ELEngine.getCallArgs(args);
        return ELEngine.invokeTarget(c, target, closures);
    }

    // ── Collections ──

    public static Object newList(Object[] elems) {
        return java.util.Arrays.asList(elems);
    }

    public static Object newMap(Object[] kvs) {
        java.util.LinkedHashMap<Object, Object> m = new java.util.LinkedHashMap<>();
        for (int i = 0; i < kvs.length; i += 2)
            m.put(kvs[i], kvs[i + 1]);
        return m;
    }

    public static Object newTuple(Object[] elems) {
        return elems;
    }

    public static Object newRange(Object begin, Object end) {
        return org.operamasks.el.eval.Ranges.createRange(
                ((Number)begin).longValue(), ((Number)end).longValue(), 1);
    }

    public static Object contains(Object coll, Object elem) {
        if (coll instanceof java.util.Collection<?> c)
            return c.contains(elem);
        if (coll instanceof Object[] a) {
            for (Object o : a)
                if (java.util.Objects.equals(o, elem))
                    return true;
            return false;
        }
        if (coll instanceof Seq seq) {
            while (!seq.isEmpty()) {
                if (java.util.Objects.equals(seq.head(), elem))
                    return true;
                seq = seq.tail();
            }
        }
        return false;
    }

    public static Object getIter(Object coll) {
        return IRInterpreter.getIterator(coll);
    }

    public static Object iterNext(Object it) {
        java.util.Iterator<?> iter = (java.util.Iterator<?>) it;
        return iter.hasNext() ? iter.next() : null;
    }

    // ── Field access ──

    public static Object loadField(Object base, String name) {
        if (base == null)
            throw new NullPointerException("Cannot read field '" + name + "' from null");
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            return f.get(target);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException("Field not found: " + name + " on " + base.getClass().getName());
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Cannot access field: " + name, e);
        }
    }

    public static Object storeFieldBC(Object value, Object base, String name) {
        if (base == null)
            throw new NullPointerException("Cannot write field '" + name + "' to null");
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            f.set(target, coerceArg(value, f.getType()));
            return value;
        } catch (NoSuchFieldException e) {
            throw new RuntimeException("Field not found: " + name + " on " + base.getClass().getName());
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Cannot access field: " + name, e);
        }
    }

    private static Object coerceArg(Object arg, Class<?> paramType) {
        if (arg == null || paramType.isInstance(arg)) return arg;
        if (arg instanceof Number n) {
            if (paramType == int.class || paramType == Integer.class) return n.intValue();
            if (paramType == long.class || paramType == Long.class) return n.longValue();
            if (paramType == double.class || paramType == Double.class) return n.doubleValue();
            if (paramType == float.class || paramType == Float.class) return n.floatValue();
            if (paramType == short.class || paramType == Short.class) return n.shortValue();
            if (paramType == byte.class || paramType == Byte.class) return n.byteValue();
        }
        return arg;
    }

    // ── Closures ──

    public static IRClosure createClosure(IRFunction fn, Object[] captured) {
        return new IRClosure(fn, captured);
    }

    // ── Locals / IncDec ──

    public static Object incLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l + 1;
        else if (val instanceof Integer i)
            val = i + 1;
        else if (val instanceof Double d)
            val = d + 1.0;
        else
            val = ((Number) val).longValue() + 1;
        locals[idx] = val;
        return val;
    }

    public static Object decLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l - 1;
        else if (val instanceof Integer i)
            val = i - 1;
        else if (val instanceof Double d)
            val = d - 1.0;
        else
            val = ((Number) val).longValue() - 1;
        locals[idx] = val;
        return val;
    }

    // ── Math ──

    public static Object intPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).intValue(), ((Number) y).intValue());
    }

    public static Object longPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).longValue(), ((Number) y).longValue());
    }

    public static Object doublePow(Object x, Object y) {
        return Math.pow(((Number) x).doubleValue(), ((Number) y).doubleValue());
    }

    // ── Bitwise ──

    public static Object bitAnd(Object a, Object b) {
        return ((Number) a).longValue() & ((Number) b).longValue();
    }

    public static Object bitOr(Object a, Object b) {
        return ((Number) a).longValue() | ((Number) b).longValue();
    }

    public static Object bitXor(Object a, Object b) {
        return ((Number) a).longValue() ^ ((Number) b).longValue();
    }

    public static Object bitShl(Object a, Object b) {
        return ((Number) a).longValue() << ((Number) b).longValue();
    }

    public static Object bitShr(Object a, Object b) {
        return ((Number) a).longValue() >> ((Number) b).longValue();
    }

    public static Object bitUshr(Object a, Object b) {
        return ((Number) a).longValue() >>> ((Number) b).longValue();
    }

    public static Object bitNot(Object a) {
        return ~((Number) a).longValue();
    }

    // ── Dynamic ops ──

    public static Object dynAdd(Object x, Object y) {
        return ((Number) x).doubleValue() + ((Number) y).doubleValue();
    }

    public static Object dynSub(Object x, Object y) {
        return ((Number) x).doubleValue() - ((Number) y).doubleValue();
    }

    public static Object dynMul(Object x, Object y) {
        return ((Number) x).doubleValue() * ((Number) y).doubleValue();
    }

    public static Object dynDiv(Object x, Object y) {
        if (x instanceof Long xl && y instanceof Long yl) {
            if (yl == 0)
                throw new ArithmeticException("/ by zero");
            return (xl % yl == 0) ? xl / yl : (double) xl / (double) yl;
        }
        if (x instanceof Integer xi && y instanceof Integer yi) {
            if (yi == 0)
                throw new ArithmeticException("/ by zero");
            return (xi % yi == 0) ? xi / yi : (double) xi / (double) yi;
        }
        return ((Number) x).doubleValue() / ((Number) y).doubleValue();
    }

    public static Object dynRem(Object x, Object y) {
        return ((Number) x).doubleValue() % ((Number) y).doubleValue();
    }

    public static Object dynNeg(Object x) {
        return -((Number) x).doubleValue();
    }

    public static Object dynPow(Object x, Object y) {
        return Math.pow(((Number) x).doubleValue(), ((Number) y).doubleValue());
    }

    public static Object dynCat(Object x, Object y) {
        return String.valueOf(x) + String.valueOf(y);
    }

    public static Object dynEq(Object x, Object y) {
        return java.util.Objects.equals(x, y);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Object dynLt(Object x, Object y) {
        if (x instanceof Comparable a && y instanceof Comparable b)
            return a.compareTo(b) < 0;
        return String.valueOf(x).compareTo(String.valueOf(y)) < 0;
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Object dynLe(Object x, Object y) {
        if (x instanceof Comparable a && y instanceof Comparable b)
            return a.compareTo(b) <= 0;
        return String.valueOf(x).compareTo(String.valueOf(y)) <= 0;
    }

    public static Object dynIn(Object x, Object y) {
        if (y instanceof java.util.Collection<?> c)
            return c.contains(x);
        return false;
    }

    // ── Type guard ──

    public static void guardTypeStrict(Object val, int typeId) {
        if (!checkGuardType(val, typeId)) {
            String expected = IRFormat.primTypeName(typeId);
            String actual = val == null ? "null" : val.getClass().getName();
            throw new RuntimeException("Type mismatch: expected " + expected + ", got " + actual);
        }
    }

    private static boolean checkGuardType(Object val, int typeId) {
        if (val == null)
            return false;
        return switch (typeId) {
            case IRFormat.T_INT ->
                    val instanceof Integer || val instanceof Short || val instanceof Byte || val instanceof Long;
            case IRFormat.T_LONG ->
                    val instanceof Long || val instanceof Integer || val instanceof Short || val instanceof Byte;
            case IRFormat.T_DOUBLE ->
                    val instanceof Double || val instanceof Float || val instanceof Long || val instanceof Integer;
            case IRFormat.T_BOOL -> val instanceof Boolean;
            case IRFormat.T_STRING -> val instanceof String;
            default -> true;
        };
    }
}
