/*
 * Copyright 2006-2026 Daniel Yuan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package elite.lang;

import javax.el.ELContext;
import javax.el.ValueExpression;

import org.operamasks.el.eval.*;
import org.operamasks.el.eval.closure.MethodClosure;
import org.operamasks.el.ir.IRClosure;
import org.operamasks.el.ir.IRFormat;
import org.operamasks.el.ir.IRFunction;
import org.operamasks.el.ir.IRInterpreter;
import org.operamasks.el.parser.ELNode;
import org.operamasks.el.resolver.MethodResolver;

import static org.operamasks.el.resources.Resources.*;

/**
 * Runtime support methods called from ELite-generated bytecode via {@code invokestatic}.
 */
public final class Runtime {

    private Runtime() {
    }

    // ── ELContext-dependent helpers ──

    public static Object pushGlobal(ELContext c, String name) {
        javax.el.ValueExpression ve = c.getVariableMapper().resolveVariable(name);
        if (ve != null)
            return ve.getValue(c);
        // Check FunctionMapper for global/imported functions
        org.operamasks.el.resolver.MethodResolver mr =
            org.operamasks.el.resolver.MethodResolver.getInstance(c);
        if (mr != null) {
            org.operamasks.el.eval.closure.MethodClosure mc =
                mr.resolveGlobalMethod(c.getFunctionMapper(), name);
            if (mc != null)
                return mc;
        }
        c.setPropertyResolved(false);
        Object r = c.getELResolver().getValue(c, null, name);
        if (c.isPropertyResolved())
            return r;
        throw new RuntimeException(_T(EL_UNDEFINED_IDENTIFIER, name));
    }

    public static Object defineGlobal(ELContext c, String name, Object value) {
        c.getVariableMapper().setVariable(name, new org.operamasks.el.eval.closure.LiteralClosure(value));
        return value;
    }

    public static Object loadProperty(ELContext c, Object base, Object key) {
        return ELNode.ACCESS.getValue(c, base, key);
    }

    public static Object storeProperty(ELContext c, Object base, Object key, Object value) {
        ELNode.ACCESS.setValue(c, base, key, value);
        return value;
    }

    public static Object trampoline(ELContext c, Object nodeObj) {
        org.operamasks.el.parser.ELNode node = (org.operamasks.el.parser.ELNode) nodeObj;
        return node.getValue(new org.operamasks.el.eval.EvaluationContext(c));
    }

    /** Evaluate a trampoline node by pool index (for bytecode — LDC can't embed ELNode). */
    public static Object trampolineById(ELContext c, int poolIdx) {
        return trampoline(c, funcPool.get()[poolIdx]);
    }

    /** Evaluate a TRY node via AST (using TryDescriptor's original TRY node). */
    public static Object trampolineTry(ELContext c, int poolIdx) {
        Object obj = funcPool.get()[poolIdx];
        if (obj instanceof org.operamasks.el.ir.TryDescriptor td) {
            return trampoline(c, td.tryNode);
        }
        return trampoline(c, obj);
    }

    /**
     * After a TRAMPOLINE causes AST evaluation (which may modify global variables
     * through the VariableMapper), sync those changes back to the local slots
     * so subsequent PUSH_VAR instructions see updated values.
     */
    public static void syncLocals(javax.el.ELContext ctx, Object[] locals, String[] varNames) {
        if (locals == null || varNames == null) return;
        javax.el.VariableMapper vm = ctx.getVariableMapper();
        for (int i = 0; i < varNames.length && i < locals.length; i++) {
            javax.el.ValueExpression ve = vm.resolveVariable(varNames[i]);
            if (ve != null) {
                locals[i] = ve.getValue(ctx);
            }
        }
    }

    /** Wrap a throwable value as RuntimeException for ATHROW bytecode. */
    public static RuntimeException wrapThrow(Object cause) {
        if (cause instanceof RuntimeException re) return re;
        if (cause instanceof Throwable t)
            return new org.operamasks.el.eval.UserException(null, t);
        if (cause instanceof String s)
            return new org.operamasks.el.eval.UserException(null, s);
        return new org.operamasks.el.eval.UserException(null);
    }

    public static Object invokeDyn(ELContext c, Object target, Object[] args) {
        Closure[] closures = ELEngine.getCallArgs(args);
        return ELEngine.invokeTarget(c, target, closures);
    }

    // ── Collections ──

    public static Object newList(Object[] elems) {
        return java.util.Arrays.asList(elems);
    }

    /** Reference/identity equality (===). */
    public static Object refEq(Object x, Object y) {
        return x == y;
    }

    /** Reference/identity inequality (!==). */
    public static Object refNe(Object x, Object y) {
        return x != y;
    }

    public static Object newMap(Object[] kvs) {
        java.util.LinkedHashMap<Object, Object> m = new java.util.LinkedHashMap<>();
        for (int i = 0; i < kvs.length; i += 2)
            m.put(kvs[i], kvs[i + 1]);
        return m;
    }

    public static Object newTuple(Object[] elems) {
        return elems;
    }

    private static boolean isChar(Object o) {
        if (o instanceof Character) {
            return true;
        } else if (o instanceof String) {
            return ((String)o).length() == 1;
        } else {
            return false;
        }
    }

    private static char getChar(Object o) {
        if (o instanceof Character) {
            return (Character)o;
        } else if (o instanceof String) {
            return ((String)o).charAt(0);
        } else {
            throw new AssertionError();
        }
    }

    public static Object newRange(Object begin, Object next, Object end) {
        if (isChar(begin) && (next == null || isChar(next)) && (end == null || isChar(end))) {
            char c_begin = getChar(begin);
            int c_step = (next == null) ? 1 : getChar(next) - c_begin;
            if (end == null) {
                return CharRanges.createUnboundedRange(c_begin, c_step);
            } else {
                char c_end = getChar(end);
                return CharRanges.createCharRange(c_begin, c_end, c_step);
            }
        } else {
            long l_begin = TypeCoercion.coerceToLong(begin);
            long l_step = (next == null) ? 1 : TypeCoercion.coerceToLong(next) - l_begin;
            if (end == null) {
                return Ranges.createUnboundedRange(l_begin, l_step);
            } else {
                long l_end = TypeCoercion.coerceToLong(end);
                return Ranges.createRange(l_begin, l_end, l_step);
            }
        }
    }

    public static Object getIter(Object coll) {
        return IRInterpreter.getIterator(coll);
    }

    public static Object iterNext(Object it) {
        java.util.Iterator<?> iter = (java.util.Iterator<?>) it;
        return iter.hasNext() ? iter.next() : null;
    }

    // ── Field access ──

    public static Object loadField(Object base, String name) {
        if (base == null)
            throw new NullPointerException(_T(IR_FIELD_READ_FROM_NULL, name));
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            return f.get(target);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(_T(IR_FIELD_NOT_FOUND, name, base.getClass().getName()));
        } catch (IllegalAccessException e) {
            throw new RuntimeException(_T(IR_FIELD_ACCESS_ERROR, name), e);
        }
    }

    public static Object storeFieldBC(Object value, Object base, String name) {
        if (base == null)
            throw new NullPointerException(_T(IR_FIELD_WRITE_TO_NULL, name));
        try {
            Class<?> cls = (base instanceof Class<?> c) ? c : base.getClass();
            java.lang.reflect.Field f = cls.getField(name);
            Object target = java.lang.reflect.Modifier.isStatic(f.getModifiers()) ? null : base;
            f.set(target, coerceArg(value, f.getType()));
            return value;
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(_T(IR_FIELD_NOT_FOUND, name, base.getClass().getName()));
        } catch (IllegalAccessException e) {
            throw new RuntimeException(_T(IR_FIELD_ACCESS_ERROR, name), e);
        }
    }

    private static Object coerceArg(Object arg, Class<?> paramType) {
        if (arg == null || paramType.isInstance(arg)) return arg;
        if (arg instanceof Number n) {
            if (paramType == int.class || paramType == Integer.class) return n.intValue();
            if (paramType == long.class || paramType == Long.class) return n.longValue();
            if (paramType == double.class || paramType == Double.class) return n.doubleValue();
            if (paramType == float.class || paramType == Float.class) return n.floatValue();
            if (paramType == short.class || paramType == Short.class) return n.shortValue();
            if (paramType == byte.class || paramType == Byte.class) return n.byteValue();
        }
        return arg;
    }

    // ── Closures ──

    private static final ThreadLocal<Object[]> funcPool =
        ThreadLocal.withInitial(() -> new Object[0]);

    /** Register constant pool for closure creation via funcIdx. */
    public static void setFuncPool(Object[] pool) { funcPool.set(pool); }
    public static void clearFuncPool() { funcPool.remove(); }

    // ── Provided arg count for default parameter handling ──
    // Uses ThreadLocal to avoid cross-thread interference in concurrent execution.
    // Per JLS §17, each thread sees its own initial value (0).

    private static final ThreadLocal<int[]> providedArgCount =
        ThreadLocal.withInitial(() -> new int[1]);

    /** Set the actual number of arguments passed (before default filling). */
    public static void setProvidedArgCount(int n) { providedArgCount.get()[0] = n; }
    /** Get the actual number of arguments passed. */
    public static int getProvidedArgCount() { return providedArgCount.get()[0]; }
    /** Clear the provided arg count (call after bytecode execution). */
    public static void clearProvidedArgCount() { providedArgCount.remove(); }

    public static IRClosure createClosure(ELContext elctx, IRFunction fn, Object[] captured) {
        // Capture evalContext so captured variables resolve in the
        // original enclosing scope. Try the ELContext first (bytecode
        // mode stores it there), then fall back to ThreadLocal.
        EvaluationContext env = (EvaluationContext)elctx.getContext(EvaluationContext.class);
        return new IRClosure(env, fn, captured);
    }

    /** Create closure by pool index (for bytecode — LDC can't embed IRFunction). */
    public static IRClosure createClosureById(ELContext elctx, int funcIdx, Object[] captured) {
        IRFunction fn = (IRFunction) funcPool.get()[funcIdx];
        return createClosure(elctx, fn, captured);
    }

    // ── Locals / IncDec ──

    public static Object incLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l + 1;
        else if (val instanceof Integer i)
            val = i + 1;
        else if (val instanceof Double d)
            val = d + 1.0;
        else
            val = ((Number) val).longValue() + 1;
        locals[idx] = val;
        return val;
    }

    public static Object decLocal(Object[] locals, int idx) {
        Object val = locals[idx];
        if (val instanceof Long l)
            val = l - 1;
        else if (val instanceof Integer i)
            val = i - 1;
        else if (val instanceof Double d)
            val = d - 1.0;
        else
            val = ((Number) val).longValue() - 1;
        locals[idx] = val;
        return val;
    }

    // ── Math ──

    public static Object intPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).intValue(), ((Number) y).intValue());
    }

    public static Object longPow(Object x, Object y) {
        return (long) Math.pow(((Number) x).longValue(), ((Number) y).longValue());
    }

    public static Object doublePow(Object x, Object y) {
        return Math.pow(((Number) x).doubleValue(), ((Number) y).doubleValue());
    }

    // ── Bitwise ──

    public static Object bitAnd(Object a, Object b) {
        return ((Number) a).longValue() & ((Number) b).longValue();
    }

    public static Object bitOr(Object a, Object b) {
        return ((Number) a).longValue() | ((Number) b).longValue();
    }

    public static Object bitXor(Object a, Object b) {
        return ((Number) a).longValue() ^ ((Number) b).longValue();
    }

    public static Object bitShl(Object a, Object b) {
        return ((Number) a).longValue() << ((Number) b).longValue();
    }

    public static Object bitShr(Object a, Object b) {
        return ((Number) a).longValue() >> ((Number) b).longValue();
    }

    public static Object bitUshr(Object a, Object b) {
        return ((Number) a).longValue() >>> ((Number) b).longValue();
    }

    public static Object bitNot(Object a) {
        return ~((Number) a).longValue();
    }

    // ── Dynamic ops ──

    public static Object dynAdd(ELContext elctx, Object x, Object y) {
        return Builtin.__add__(elctx, x, y);
    }

    public static Object dynSub(ELContext elctx, Object x, Object y) {
        return Builtin.__sub__(elctx, x, y);
    }

    public static Object dynMul(ELContext elctx, Object x, Object y) {
        return Builtin.__mul__(elctx, x, y);
    }

    public static Object dynDiv(ELContext elctx, Object x, Object y) {
        return Builtin.__div__(elctx, x, y);
    }

    public static Object dynRem(ELContext elctx, Object x, Object y) {
        return Builtin.__rem__(elctx, x, y);
    }

    public static Object dynPow(ELContext elctx, Object x, Object y) {
        return Builtin.__pow__(elctx, x, y);
    }

    public static Object dynCat(ELContext elctx, Object x, Object y) {
        return Builtin.__cat__(elctx, x, y);
    }

    private static final ELNode.NEG __NEG__ = new ELNode.NEG(-1, null);

    public static Object dynNeg(ELContext elctx, Object x) {
        return __NEG__.getValue(elctx, x);
    }

    public static Object dynShl(ELContext elctx, Object x, Object y) {
        return Builtin.__shl__(elctx, x, y);
    }

    public static Object dynShr(ELContext elctx, Object x, Object y) {
        return Builtin.__shr__(elctx, x, y);
    }

    public static Object dynUShr(ELContext elctx, Object x, Object y) {
        return Builtin.__ushr__(elctx, x, y);
    }

    public static Object dynEq(ELContext elctx, Object x, Object y) {
        return Builtin.__eq__(elctx, x, y);
    }

    public static Object dynNe(ELContext elctx, Object x, Object y) {
        return Builtin.__ne__(elctx, x, y);
    }

    public static Object dynLt(ELContext elctx, Object x, Object y) {
        return Builtin.__lt__(elctx, x, y);
    }

    public static Object dynLe(ELContext elctx, Object x, Object y) {
        return Builtin.__le__(elctx, x, y);
    }

    public static Object dynGt(ELContext elctx, Object x, Object y) {
        return Builtin.__gt__(elctx, x, y);
    }

    public static Object dynGe(ELContext elctx, Object x, Object y) {
        return Builtin.__ge__(elctx, x, y);
    }

    public static Object dynBitAnd(ELContext elctx, Object x, Object y) {
        return Builtin.__bitand__(elctx, x, y);
    }

    public static Object dynBitOr(ELContext elctx, Object x, Object y) {
        return Builtin.__bitor__(elctx, x, y);
    }

    public static Object dynXor(ELContext elctx, Object x, Object y) {
        return Builtin.__xor__(elctx, x, y);
    }

    public static Object dynBitNot(ELContext elctx, Object x) {
        return Builtin.__bitnot__(elctx, x);
    }

    private static final ELNode.EMPTY __EMPTY__ = new ELNode.EMPTY(-1, null);
    public static Object dynEmpty(ELContext elctx, Object x) {
        return __EMPTY__.getValue(elctx, x);
    }

    private static final ELNode.IN __IN__ = new ELNode.IN(-1, null, null, false);
    public static Object dynIn(ELContext elctx, Object coll, Object elem) {
        return __IN__.eval(elctx, elem, coll);
    }

    // ── Dynamic invocation ──

    public static Object resolveGlobal(EvaluationContext context, String id) {
        ELContext elctx = context.getELContext();

        ValueExpression expr = context.resolveVariable(id);
        if (expr != null) {
            return expr.getValue(elctx);
        }

        elctx.setPropertyResolved(false);
        Object value = elctx.getELResolver().getValue(elctx, null, id);
        if (elctx.isPropertyResolved()) {
            return value;
        }

        MethodClosure method = MethodResolver.getInstance(elctx)
            .resolveGlobalMethod(context.getFunctionMapper(), id);
        if (method != null) {
            return method;
        }

        throw new EvaluationException(elctx, _T(EL_UNDEFINED_IDENTIFIER, id));
    }

    public static Object resolveTarget(EvaluationContext context, String id) {
        ELContext elctx = context.getELContext();

        ValueExpression expr = context.resolveVariable(id);
        if (expr != null)
            return (expr instanceof Closure) ? expr : expr.getValue(elctx);

        MethodClosure method = MethodResolver.getInstance(elctx)
            .resolveGlobalMethod(context.getFunctionMapper(), id);
        if (method != null)
            return method;

        elctx.setPropertyResolved(false);
        return elctx.getELResolver().getValue(elctx, null, id);
    }

    public static Object invokeTarget(EvaluationContext context, String id, Object[] args) {
        ELContext elctx = context.getELContext();
        Object target = resolveTarget(context, id);
        if (target == null)
            throw new EvaluationException(elctx, _T(EL_UNDEFINED_IDENTIFIER, id));

        try {
            return ELEngine.invokeTarget(elctx, target, ELEngine.getCallArgs(args));
        } catch (RuntimeException ex) {
            throw new EvaluationException(elctx, ex);
        }
    }

    public static Object invokeDynMethod(ELContext elctx, Object base, Object key, Object[] args) {
        return ELNode.ACCESS.invoke(elctx, base, key, ELEngine.getCallArgs(args));
    }

    // ── Type guard ──

    public static void guardTypeStrict(Object val, int typeId) {
        if (!checkGuardType(val, typeId)) {
            String expected = IRFormat.primTypeName(typeId);
            String actual = val == null ? "null" : val.getClass().getName();
            throw new RuntimeException(_T(IR_TYPE_MISMATCH, expected, actual));
        }
    }

    private static boolean checkGuardType(Object val, int typeId) {
        if (val == null)
            return false;
        return switch (typeId) {
            case IRFormat.T_INT ->
                    val instanceof Integer || val instanceof Short || val instanceof Byte || val instanceof Long;
            case IRFormat.T_LONG ->
                    val instanceof Long || val instanceof Integer || val instanceof Short || val instanceof Byte;
            case IRFormat.T_DOUBLE ->
                    val instanceof Double || val instanceof Float || val instanceof Long || val instanceof Integer;
            case IRFormat.T_BOOL -> val instanceof Boolean;
            case IRFormat.T_STRING -> val instanceof String;
            default -> true;
        };
    }
}
